import type { Category } from './index'

/**
 * Ninth batch, fünf und sechs Buchstaben.
 *
 * Gleiche Quellen wie Grundwortschatz VIII. Die Häufigkeitsliste stammt aus
 * Filmuntertiteln und enthält reichlich Kraftausdrücke, Beleidigungen und
 * Markennamen — die sind hier von Hand aussortiert, ebenso Vornamen und
 * englische Wörter ohne Fuss im Deutschen.
 *
 * Fünf und sechs Buchstaben sind die Längen, die ein Gitter tragen: sie füllen
 * die langen Läufe, während die Dreier und Vierer die Ecken schliessen.
 */
export const grundwortschatz9: Category = {
  id: 'grundwortschatz9',
  label: 'Grundwortschatz IX',
  always: true,
  entries: [
    ['Achse', 'Gedachte Linie der Drehung'],
    ['Acker', 'Bestelltes Feld des Bauern'],
    ['Ahnung', 'Vages Gefühl für Kommendes'],
    ['Aktion', 'Zielgerichtete Handlung'],
    ['Allee', 'Strasse mit Bäumen an beiden Seiten'],
    ['Anbau', 'Angesetzter Teil am Haus'],
    ['Anfall', 'Plötzlicher Ausbruch der Krankheit'],
    ['Anflug', 'Annäherung des Flugzeugs'],
    ['Anlage', 'Technische Einrichtung'],
    ['Anlass', 'Grund für eine Feier'],
    ['Anmut', 'Reiz der Bewegung'],
    ['Anteil', 'Zustehender Teil vom Ganzen'],
    ['Aorta', 'Grosse Schlagader am Herzen'],
    ['Archiv', 'Sammlung alter Akten'],
    ['Areal', 'Abgegrenztes Gelände'],
    ['Arsen', 'Giftiges Halbmetall'],
    ['Ballon', 'Luftgefüllte Hülle zum Steigen'],
    ['Bandit', 'Räuber auf eigene Faust'],
    ['Bedarf', 'Was gebraucht wird'],
    ['Beben', 'Erschütterung der Erde'],
    ['Beginn', 'Erster Augenblick'],
    ['Benimm', 'Gutes Betragen'],
    ['Besitz', 'Was jemandem gehört'],
    ['Bestie', 'Wildes grausames Tier'],
    ['Betrag', 'Summe in Zahlen'],
    ['Betrug', 'Täuschung zum eigenen Vorteil'],
    ['Biker', 'Fahrer einer schweren Maschine'],
    ['Bluff', 'Vorgetäuschte Stärke'],
    ['Bowle', 'Getränk mit Früchten im Glas'],
    ['Budget', 'Geplanter Rahmen der Ausgaben'],
    ['Butler', 'Diener im englischen Haus'],
    ['Campus', 'Gelände der Hochschule'],
    ['Casino', 'Haus des Glücksspiels'],
    ['Chefin', 'Frau an der Spitze'],
    ['Christ', 'Anhänger der Lehre Jesu'],
    ['Chrom', 'Glänzendes Metall am Auto'],
    ['Cognac', 'Edler Weinbrand aus Frankreich'],
    ['Cowboy', 'Rinderhirt im Wilden Westen'],
    ['Creme', 'Salbe für die Haut'],
    ['Daheim', 'In den eigenen vier Wänden'],
    ['Dealer', 'Händler mit verbotener Ware'],
    ['Deckel', 'Verschluss des Topfes'],
    ['Defekt', 'Schaden an der Technik'],
    ['Demut', 'Bescheidene Haltung'],
    ['Depot', 'Lager für Vorräte'],
    ['Derby', 'Spiel der Nachbarn im Sport'],
    ['Design', 'Gestaltung der Form'],
    ['Detail', 'Kleine Einzelheit'],
    ['Dinner', 'Festliches Abendessen'],
    ['Disko', 'Ort zum Tanzen, kurz'],
    ['Dollar', 'Währung in den Staaten'],
    ['Drohne', 'Fliegendes Gerät ohne Pilot'],
    ['Duett', 'Stück für zwei Stimmen'],
    ['Düse', 'Enge Öffnung für den Strahl'],
    ['Effekt', 'Erzielte Wirkung'],
    ['Entzug', 'Weg heraus aus der Sucht'],
    ['Enzym', 'Eiweiss als Beschleuniger'],
    ['Erbin', 'Frau, die das Vermögen bekommt'],
    ['Ersatz', 'Was an die Stelle tritt'],
    ['Ethik', 'Lehre vom rechten Handeln'],
    ['Fabrik', 'Halle der Herstellung'],
    ['Farce', 'Derbes Lustspiel'],
    ['Farmer', 'Bauer in Übersee'],
    ['Faser', 'Dünner Faden im Gewebe'],
    ['Fazit', 'Ergebnis am Ende'],
    ['Fehde', 'Alter Streit zweier Sippen'],
    ['Felsen', 'Grosser Block aus Stein'],
    ['Filet', 'Bestes Stück vom Fleisch'],
    ['Finte', 'Täuschende Bewegung'],
    ['Flagge', 'Tuch am Mast'],
    ['Flirt', 'Spielerisches Werben'],
    ['Flyer', 'Blatt für die Werbung'],
    ['Fokus', 'Punkt der Schärfe'],
    ['Folie', 'Dünne Schicht aus Kunststoff'],
    ['Folter', 'Quälerei zum Geständnis'],
    ['Fonds', 'Topf mit angelegtem Geld'],
    ['Forum', 'Platz für die Aussprache'],
    ['Foyer', 'Halle vor dem Saal'],
    ['Frack', 'Festlicher Rock des Herrn'],
    ['Frust', 'Gefühl nach dem Scheitern'],
    ['Funken', 'Winziger glühender Splitter'],
    ['Furie', 'Rasende Rachegöttin'],
    ['Futter', 'Nahrung für das Vieh'],
    ['Gamma', 'Dritter Buchstabe der Griechen'],
    ['Gatte', 'Angetrauter Mann'],
    ['Gattin', 'Angetraute Frau'],
    ['Gauner', 'Kleiner Betrüger'],
    ['Gegend', 'Landstrich in der Umgebung'],
    ['Gegner', 'Wer sich entgegenstellt'],
    ['Genom', 'Gesamtes Erbgut'],
    ['Genre', 'Gattung in der Kunst'],
    ['Gerede', 'Geschwätz ohne Gehalt'],
    ['Gesang', 'Vortrag mit der Stimme'],
    ['Gewalt', 'Rohe Anwendung von Kraft'],
    ['Gewebe', 'Verband gleicher Zellen'],
    ['Grauen', 'Tiefes Entsetzen'],
    ['Greis', 'Sehr alter Mann'],
    ['Grips', 'Verstand, umgangssprachlich'],
    ['Hacker', 'Eindringling im fremden Rechner'],
    ['Harem', 'Frauenhaus im Morgenland'],
    ['Heimat', 'Ort der Herkunft'],
    ['Heldin', 'Frau mit grossem Mut'],
    ['Helfer', 'Wer zur Hand geht'],
    ['Helix', 'Schraubenförmige Windung'],
    ['Hengst', 'Männliches Pferd'],
    ['Henne', 'Weibliches Huhn'],
    ['Herrin', 'Gebieterin über das Haus'],
    ['Herzog', 'Hoher Adelstitel'],
    ['Hirte', 'Hüter der Herde'],
    ['Hocke', 'Haltung mit gebeugten Knien'],
    ['Hoheit', 'Anrede für den Fürsten'],
    ['Husten', 'Stossen aus der Lunge'],
    ['Hymne', 'Feierliches Lied des Landes'],
    ['Ikone', 'Heiligenbild im Osten'],
    ['Impuls', 'Anstoss von aussen'],
    ['Indiz', 'Anzeichen vor Gericht'],
    ['Inhalt', 'Was drin steckt'],
    ['Ironie', 'Feiner Spott mit Gegenteil'],
    ['Islam', 'Weltreligion des Propheten'],
    ['Jacht', 'Schnelles Boot der Reichen'],
    ['Jammer', 'Lautes Klagen im Elend'],
    ['Jersey', 'Weiches gewirktes Tuch'],
    ['Junior', 'Der Jüngere von beiden'],
    ['Justiz', 'Gesamte Rechtsprechung'],
    ['Kammer', 'Kleiner Raum im Haus'],
    ['Karat', 'Mass für reines Gold'],
    ['Karton', 'Schachtel aus Pappe'],
    ['Kasten', 'Behälter mit Deckel'],
    ['Kaviar', 'Teurer Rogen vom Stör'],
    ['Kerker', 'Finsteres altes Gefängnis'],
    ['Killer', 'Mörder gegen Bezahlung'],
    ['Kiosk', 'Häuschen für Zeitungen'],
    ['Kippe', 'Rest der Zigarette'],
    ['Klappe', 'Deckel zum Zuschlagen'],
    ['Klaps', 'Leichter Schlag mit der Hand'],
    ['Klemme', 'Missliche Lage'],
    ['Klick', 'Druck auf die Maustaste'],
    ['Klient', 'Kunde des Anwalts'],
    ['Klinik', 'Haus für die Kranken'],
    ['Klotz', 'Plumper schwerer Block'],
    ['Knete', 'Formbare Masse für Kinder'],
    ['Knick', 'Scharfe Biegung im Papier'],
    ['Kneipe', 'Einfache Wirtschaft'],
    ['Kombi', 'Wagen mit grossem Heck'],
    ['Komik', 'Was zum Lachen reizt'],
    ['Korps', 'Grosser Verband der Truppe'],
    ['Kredit', 'Geliehenes Geld der Bank'],
    ['Kripo', 'Kriminalpolizei, kurz'],
    ['Kumpel', 'Guter Kamerad, auch Bergmann'],
    ['Kurier', 'Bote mit dringender Sendung'],
    ['Label', 'Firma hinter der Musik'],
    ['Ladung', 'Fracht auf dem Laster'],
    ['Lakai', 'Unterwürfiger Diener'],
    ['Lappen', 'Tuch zum Putzen'],
    ['Latex', 'Milchsaft des Kautschuks'],
    ['Leiche', 'Toter Körper'],
    ['Leier', 'Zupfinstrument der Antike'],
    ['Lepra', 'Aussatz als Krankheit'],
    ['Limit', 'Festgesetzte Grenze'],
    ['Lizenz', 'Erlaubnis zur Nutzung'],
    ['Logik', 'Lehre vom folgerichtigen Denken'],
    ['Lotto', 'Spiel mit sechs Zahlen'],
    ['Lücke', 'Offene Stelle in der Reihe'],
    ['Lumen', 'Einheit für den Lichtstrom'],
    ['Macke', 'Wunderliche Eigenart'],
    ['Madame', 'Anrede der Dame in Paris'],
    ['Magier', 'Meister der Zauberkunst'],
    ['Mappe', 'Hülle für Papiere'],
    ['Marina', 'Hafen für Sportboote'],
    ['Marine', 'Streitkraft auf dem Wasser'],
    ['Medium', 'Träger der Nachricht'],
    ['Mekka', 'Heilige Stadt am Roten Meer'],
    ['Mentor', 'Erfahrener Ratgeber'],
    ['Metall', 'Glänzender leitender Stoff'],
    ['Meute', 'Rudel jagender Hunde'],
    ['Mieter', 'Wer die Wohnung bezahlt'],
    ['Milan', 'Greifvogel mit gegabeltem Stoss'],
    ['Milde', 'Nachsicht im Urteil'],
    ['Miliz', 'Bewaffnete Bürgerwehr'],
    ['Minze', 'Kraut für den Tee'],
    ['Mittel', 'Weg zum Zweck'],
    ['Modell', 'Kleine Nachbildung'],
    ['Modul', 'Austauschbarer Baustein'],
    ['Modus', 'Art und Weise des Vorgehens'],
    ['Mokka', 'Sehr starker kleiner Kaffee'],
    ['Moment', 'Ganz kurzer Augenblick'],
    ['Moped', 'Kleines Krad für Jugendliche'],
    ['Mythos', 'Alte Erzählung der Götter'],
    ['Nation', 'Volk mit eigenem Staat'],
    ['Neige', 'Letzter Rest im Glas'],
    ['Ninja', 'Kämpfer im Schatten Japans'],
    ['Niveau', 'Erreichte Höhe des Könnens'],
    ['Nummer', 'Kennzeichen aus Ziffern'],
    ['Objekt', 'Ding der Betrachtung'],
    ['Omega', 'Letzter Buchstabe der Griechen'],
    ['Opium', 'Saft des Schlafmohns'],
    ['Optik', 'Lehre vom Licht'],
    ['Option', 'Offene Möglichkeit der Wahl'],
    ['Order', 'Bindender Auftrag'],
    ['Organ', 'Teil des Körpers mit Aufgabe'],
    ['Orgie', 'Masslos ausuferndes Gelage'],
    ['Orion', 'Sternbild mit drei Gürtelsternen'],
    ['Outfit', 'Zusammengestellte Kleidung'],
    ['Pacht', 'Miete für Land'],
    ['Palast', 'Prunkvoller Wohnbau'],
    ['Pampa', 'Weite Grasebene in Argentinien'],
    ['Pappe', 'Dicker steifer Karton'],
    ['Parade', 'Aufmarsch in Reih und Glied'],
    ['Partie', 'Einzelne Runde im Spiel'],
    ['Pasta', 'Teigware aus Italien'],
    ['Pastor', 'Geistlicher der Gemeinde'],
    ['Pedal', 'Hebel für den Fuss'],
    ['Person', 'Einzelner Mensch'],
    ['Petze', 'Wer alles verrät'],
    ['Pflege', 'Sorgsame Betreuung'],
    ['Piano', 'Tasteninstrument, auch leise'],
    ['Piste', 'Bahn für die Skifahrer'],
    ['Platte', 'Flacher runder Tonträger'],
    ['Pleite', 'Zahlungsunfähigkeit'],
    ['Poesie', 'Dichtung in Versen'],
    ['Polka', 'Schneller Tanz aus Böhmen'],
    ['Posten', 'Stelle im Betrieb'],
    ['Praxis', 'Räume des Arztes'],
    ['Profil', 'Umriss von der Seite'],
    ['Profit', 'Gewinn aus dem Geschäft'],
    ['Promi', 'Bekanntes Gesicht, kurz'],
    ['Psalm', 'Lied aus der Bibel'],
    ['Qualm', 'Dichter beissender Rauch'],
    ['Quote', 'Festgelegter Anteil'],
    ['Radau', 'Lauter Lärm'],
    ['Radon', 'Radioaktives Edelgas'],
    ['Rampe', 'Schiefe Ebene zum Verladen'],
    ['Rasur', 'Entfernen der Barthaare'],
    ['Razzia', 'Plötzlicher Zugriff der Polizei'],
    ['Region', 'Grösserer Landstrich'],
    ['Reibe', 'Küchengerät für Käse'],
    ['Rektor', 'Leiter der Hochschule'],
    ['Retter', 'Wer aus der Not hilft'],
    ['Revue', 'Bunte Schau mit Tanz'],
    ['Ritual', 'Stets gleicher Ablauf'],
    ['Rover', 'Fahrzeug auf fremden Planeten'],
    ['Rowdy', 'Randalierender Kerl'],
    ['Rubel', 'Währung in Moskau'],
    ['Rubin', 'Roter kostbarer Stein'],
    ['Rumpf', 'Körper ohne Glieder'],
    ['Rutsch', 'Gleitende Bewegung abwärts'],
    ['Saison', 'Zeit der Hochkonjunktur'],
    ['Salto', 'Sprung mit Überschlag'],
    ['Salve', 'Schüsse aus vielen Läufen'],
    ['Satin', 'Glänzendes glattes Gewebe'],
    ['Sauna', 'Kabine mit heissen Steinen'],
    ['Scout', 'Später Entdecker der Talente'],
    ['Sektor', 'Abgeteilter Bereich'],
    ['Sender', 'Anstalt für Funk und Bild'],
    ['Senior', 'Der Ältere von beiden'],
    ['Senke', 'Mulde im Gelände'],
    ['Sherry', 'Spanischer Likörwein'],
    ['Siegel', 'Abdruck im heissen Wachs'],
    ['Sieger', 'Wer den Wettkampf gewinnt'],
    ['Sigma', 'Griechischer Buchstabe'],
    ['Signal', 'Zeichen zum Handeln'],
    ['Single', 'Alleinlebender Mensch'],
    ['Sippe', 'Weit verzweigte Verwandtschaft'],
    ['Sitte', 'Überlieferter Brauch'],
    ['Skala', 'Reihe der Messwerte'],
    ['Skalp', 'Erbeutete Kopfhaut'],
    ['Sklave', 'Unfreier Mensch im Besitz'],
    ['Snack', 'Kleiner Happen zwischendurch'],
    ['Socken', 'Kurze Strümpfe'],
    ['Soldat', 'Angehöriger der Armee'],
    ['Spott', 'Verletzender Hohn'],
    ['Spruch', 'Kurzer treffender Satz'],
    ['Status', 'Rang in der Gesellschaft'],
    ['Stelle', 'Bestimmter Ort, auch Posten'],
    ['Stille', 'Völlige Ruhe ohne Laut'],
    ['Stress', 'Anhaltende Anspannung'],
    ['Strich', 'Gezogene Linie'],
    ['Stuck', 'Zierrat aus Gips'],
    ['Studie', 'Wissenschaftliche Untersuchung'],
    ['Studio', 'Raum für Aufnahmen'],
    ['Stute', 'Weibliches Pferd'],
    ['Sultan', 'Herrscher im Morgenland'],
    ['Sünde', 'Verstoss gegen das Gebot'],
    ['Swing', 'Schwungvolle Spielart des Jazz'],
    ['System', 'Geordnetes Gefüge'],
    ['Taktik', 'Kluges Vorgehen im Einzelnen'],
    ['Taler', 'Alte silberne Münze'],
    ['Talon', 'Abschnitt am Schein'],
    ['Tanga', 'Sehr knapper Badeslip'],
    ['Tanke', 'Zapfstelle, umgangssprachlich'],
    ['Tatort', 'Platz des Verbrechens'],
    ['Tausch', 'Ware gegen Ware'],
    ['Teint', 'Farbe der Gesichtshaut'],
    ['Tesla', 'Einheit der Flussdichte'],
    ['Teufel', 'Herr der Unterwelt'],
    ['Theta', 'Griechischer Buchstabe'],
    ['These', 'Behauptung zur Prüfung'],
    ['Ticket', 'Karte für die Fahrt'],
    ['Timing', 'Wahl des richtigen Zeitpunkts'],
    ['Torso', 'Rumpf einer Statue'],
    ['Totem', 'Wappentier eines Stammes'],
    ['Tramp', 'Wanderer ohne festes Ziel'],
    ['Trauma', 'Seelische Wunde'],
    ['Trend', 'Erkennbare Richtung'],
    ['Trunk', 'Kräftiger Schluck'],
    ['Truppe', 'Verband von Soldaten'],
    ['Trupp', 'Kleine Schar von Leuten'],
    ['Turner', 'Sportler am Reck'],
    ['Tusch', 'Kurzer Gruss der Kapelle'],
    ['Tutor', 'Betreuer der Studenten'],
    ['Umbau', 'Änderung am Gebäude'],
    ['Umfeld', 'Was jemanden umgibt'],
    ['Umgang', 'Verkehr mit anderen'],
    ['Umhang', 'Loser Mantel ohne Ärmel'],
    ['Unfall', 'Missgeschick mit Schaden'],
    ['Unheil', 'Grosses drohendes Übel'],
    ['Unruhe', 'Zustand ohne Frieden'],
    ['Unsinn', 'Rede ohne jeden Sinn'],
    ['Untat', 'Schlimme böse Tat'],
    ['Verrat', 'Preisgabe an den Feind'],
    ['Vetter', 'Sohn von Onkel und Tante'],
    ['Vikar', 'Geistlicher in der Ausbildung'],
    ['Viola', 'Bratsche im Orchester'],
    ['Visier', 'Klappe am Helm'],
    ['Vision', 'Bild einer fernen Zukunft'],
    ['Visum', 'Sichtvermerk im Pass'],
    ['Warze', 'Knötchen auf der Haut'],
    ['Wärme', 'Angenehm hohe Temperatur'],
    ['Wonne', 'Tiefes stilles Glück'],
    ['Zarin', 'Herrscherin in Russland'],
    ['Zauber', 'Wirkung der Magie'],
    ['Zeche', 'Rechnung im Wirtshaus'],
    ['Zombie', 'Untoter aus dem Gruselfilm'],
    ['Zugang', 'Weg hinein'],
    ['Zwirn', 'Gedrehter fester Faden'],
    ['Zyste', 'Blase mit Flüssigkeit im Gewebe']
  ]
}
