import type { Category } from './index'

/**
 * Eighth batch, drei und vier Buchstaben.
 *
 * Die Kandidaten stammen aus zwei öffentlichen Quellen: einer Substantivliste
 * aus dem deutschen Wiktionary (gambolputty/german-nouns, rund 100.000 Lemmata
 * mit Genus) und einer Häufigkeitsliste aus Untertiteln (hermitdave/
 * FrequencyWords, de_50k). Die Schnittmenge beider Listen, abzüglich allem, was
 * schon im Pool steht, ergibt die Auswahl — Fragen sind von Hand geschrieben,
 * dafür taugt keine Wortliste.
 *
 * Drei Buchstaben ist der Engpass des Generators: ein lückenloses Gitter
 * braucht kurze Läufe überall dort, wo sonst ein blockiertes Feld stünde, und
 * jeder davon kreuzt sich beidseitig. Deutsche Dreibuchstaben-Substantive sind
 * schnell erschöpft, deshalb stehen hier auch Abkürzungen, Vorsilben und
 * Lehnwörter, so wie in jedem gedruckten Schwedenrätsel.
 */
export const grundwortschatz8: Category = {
  id: 'grundwortschatz8',
  label: 'Grundwortschatz VIII',
  always: true,
  entries: [
    // --- drei Buchstaben ---
    ['Abi', 'Reifezeugnis, kurz'],
    ['Ade', 'Abschiedsgruss von früher'],
    ['Aha', 'Laut des Verstehens'],
    ['Akw', 'Meiler für Strom, kurz'],
    ['Ale', 'Obergäriges englisches Bier'],
    ['Ami', 'Umgangssprachlich: US-Bürger'],
    ['Are', 'Hundert Quadratmeter'],
    ['Bio', 'Vorsilbe für ökologisch'],
    ['Bö', 'Plötzlicher Windstoss'],
    ['Bor', 'Element mit dem Zeichen B'],
    ['Brd', 'Deutschland als Kürzel'],
    ['Ceo', 'Konzernchef auf Englisch'],
    ['Chi', 'Lebensenergie in Fernost'],
    ['Dax', 'Deutscher Aktienindex'],
    ['Ddr', 'Früherer deutscher Staat, kurz'],
    ['Dia', 'Bild für den Projektor'],
    ['Dna', 'Träger der Erbinformation'],
    ['Elm', 'Höhenzug bei Braunschweig'],
    ['Eta', 'Griechischer Buchstabe'],
    ['Feh', 'Pelz vom Eichhörnchen'],
    ['Fit', 'In guter Verfassung'],
    ['Fun', 'Spass auf Englisch'],
    ['Geo', 'Vorsilbe für die Erde'],
    ['Ger', 'Wurfspiess der Antike'],
    ['Hub', 'Weg eines Kolbens'],
    ['Ide', 'Karpfenfisch der Flüsse'],
    ['Ilm', 'Fluss durch Weimar'],
    ['Inn', 'Fluss durch Tirol zur Donau'],
    ['Ire', 'Bewohner der grünen Insel'],
    ['Kar', 'Mulde im Hochgebirge'],
    ['Kit', 'Bausatz auf Englisch'],
    ['Kot', 'Ausscheidung der Tiere'],
    ['Lkw', 'Laster, kurz'],
    ['Lok', 'Zugmaschine der Bahn'],
    ['Lux', 'Einheit der Beleuchtung'],
    ['Mir', 'Frühere Raumstation Russlands'],
    ['Moa', 'Ausgestorbener Riesenvogel'],
    ['Nah', 'Nicht weit entfernt'],
    ['Neo', 'Vorsilbe für neu'],
    ['Nie', 'Zu keiner Zeit'],
    ['Non', 'Gebetsstunde am Nachmittag'],
    ['Oft', 'Immer wieder, häufig'],
    ['Olm', 'Blinder Lurch der Höhlen'],
    ['Ork', 'Finstere Gestalt bei Tolkien'],
    ['Pan', 'Griechischer Hirtengott'],
    ['Pas', 'Schritt im Ballett'],
    ['Per', 'Mittels, durch'],
    ['Phi', 'Griechischer Buchstabe'],
    ['Pro', 'Dafür, befürwortend'],
    ['Pur', 'Rein und unvermischt'],
    ['Ren', 'Hirsch des hohen Nordens'],
    ['Rho', 'Griechischer Buchstabe'],
    ['Rio', 'Stadt am Zuckerhut, kurz'],
    ['Ruh', 'Stille in der Dichtung'],
    ['Sen', 'Kleine Münze in Japan'],
    ['Sms', 'Kurznachricht aufs Handy'],
    ['Sol', 'Römischer Sonnengott'],
    ['Sou', 'Alte Münze in Frankreich'],
    ['Suv', 'Hoher Geländewagen, kurz'],
    ['Tao', 'Weg in der Lehre des Laotse'],
    ['Tic', 'Nervöses Zucken'],
    ['Uni', 'Hochschule, kurz'],
    ['Usa', 'Staatenbund in Nordamerika'],
    ['Weh', 'Schmerz in der Dichtung'],
    ['Yen', 'Währung in Japan'],

    // --- vier Buchstaben ---
    ['Ahne', 'Vorfahr im Stammbaum'],
    ['Akne', 'Pickel in der Pubertät'],
    ['Akut', 'Plötzlich und dringend'],
    ['Aura', 'Ausstrahlung eines Menschen'],
    ['Azur', 'Tiefes Himmelblau'],
    ['Bann', 'Ausschluss aus der Gemeinschaft'],
    ['Beat', 'Grundschlag der Musik'],
    ['Beta', 'Zweiter Buchstabe der Griechen'],
    ['Boje', 'Schwimmendes Seezeichen'],
    ['Born', 'Quelle in der Dichtung'],
    ['Brei', 'Weiche Speise für Babys'],
    ['Brie', 'Weichkäse aus Frankreich'],
    ['Bude', 'Einfache Behausung'],
    ['Butt', 'Plattfisch der Nordsee'],
    ['Chat', 'Gespräch im Netz'],
    ['Chip', 'Winziger Baustein im Rechner'],
    ['Clip', 'Kurzer Film zur Musik'],
    ['Clou', 'Glanzpunkt einer Sache'],
    ['Code', 'Vorschrift zum Verschlüsseln'],
    ['Cord', 'Stoff mit Rippen'],
    ['Demo', 'Zug mit Transparenten'],
    ['Dino', 'Urzeitechse, kurz'],
    ['Diva', 'Gefeierte Künstlerin'],
    ['Doge', 'Oberhaupt in alten Venedig'],
    ['Doku', 'Film über Tatsachen, kurz'],
    ['Dutt', 'Knoten im Haar'],
    ['Edda', 'Altes Liederbuch des Nordens'],
    ['Emir', 'Fürst im Morgenland'],
    ['Eros', 'Gott der Liebe bei den Griechen'],
    ['Euro', 'Währung in zwanzig Ländern'],
    ['Exil', 'Erzwungener Aufenthalt im Ausland'],
    ['Expo', 'Weltausstellung, kurz'],
    ['Fake', 'Fälschung auf Englisch'],
    ['Fete', 'Ausgelassene Feier'],
    ['Fett', 'Energiereicher Nährstoff'],
    ['Fond', 'Rückbank im Auto'],
    ['Foto', 'Bild aus der Kamera'],
    ['Fund', 'Entdeckter Gegenstand'],
    ['Gala', 'Festliche Veranstaltung'],
    ['Gott', 'Höchstes Wesen im Glauben'],
    ['Graf', 'Adelstitel unter dem Fürsten'],
    ['Gral', 'Gesuchter Kelch der Sage'],
    ['Gram', 'Tiefer stiller Kummer'],
    ['Gran', 'Sehr altes Gewichtsmass'],
    ['Grog', 'Heisses Getränk mit Rum'],
    ['Gros', 'Grösster Teil einer Menge'],
    ['Guru', 'Geistiger Lehrer in Indien'],
    ['Hang', 'Geneigte Seite des Berges'],
    ['Heli', 'Hubschrauber, kurz'],
    ['Hohn', 'Bissiger Spott'],
    ['Hort', 'Sicherer Platz, auch Schatz'],
    ['Idol', 'Verehrtes Vorbild'],
    ['Imam', 'Vorbeter in der Moschee'],
    ['Inch', 'Zoll als englisches Mass'],
    ['Jeep', 'Robuster Geländewagen'],
    ['Jojo', 'Spielzeug an der Schnur'],
    ['Jura', 'Studium der Gesetze'],
    ['Jury', 'Gremium der Preisrichter'],
    ['Kali', 'Salz als Dünger'],
    ['Kilt', 'Rock der Schotten'],
    ['Kinn', 'Unterster Teil des Gesichts'],
    ['Kita', 'Haus für kleine Kinder, kurz'],
    ['Klan', 'Sippe der Schotten'],
    ['Klon', 'Erbgleiche Kopie'],
    ['Klub', 'Verein der Gleichgesinnten'],
    ['Koje', 'Schlafstelle auf dem Schiff'],
    ['Koma', 'Tiefe Bewusstlosigkeit'],
    ['Kost', 'Das tägliche Essen'],
    ['Kuli', 'Stift mit Kugel'],
    ['Kult', 'Verehrung mit festen Bräuchen'],
    ['Kuss', 'Zärtlichkeit mit den Lippen'],
    ['Laie', 'Jemand ohne Fachwissen'],
    ['Lenz', 'Frühling in der Dichtung'],
    ['Lift', 'Aufzug im Haus'],
    ['Lira', 'Frühere Währung Italiens'],
    ['Loge', 'Abgetrennter Platz im Theater'],
    ['Lore', 'Kleiner Wagen auf Schienen'],
    ['Lump', 'Verachtenswerter Kerl'],
    ['Lyra', 'Leier der Antike'],
    ['Maat', 'Dienstgrad auf See'],
    ['Maid', 'Junges Mädchen, veraltet'],
    ['Mama', 'Vertrauter Name der Mutter'],
    ['Mate', 'Tee aus Südamerika'],
    ['Milz', 'Organ neben dem Magen'],
    ['Mine', 'Stollen unter Tage'],
    ['Mode', 'Wechselnder Geschmack der Zeit'],
    ['Mofa', 'Kleines Motorrad mit Pedalen'],
    ['Moll', 'Weiches Tongeschlecht'],
    ['Mops', 'Kleiner Hund mit Faltengesicht'],
    ['Mord', 'Schwerste Tötung'],
    ['Most', 'Frisch gepresster Saft'],
    ['Muli', 'Kreuzung aus Pferd und Esel'],
    ['Muse', 'Göttin der schönen Künste'],
    ['Navi', 'Gerät für die Route, kurz'],
    ['Neon', 'Edelgas in der Leuchtröhre'],
    ['Nerz', 'Marder mit begehrtem Pelz'],
    ['Norm', 'Verbindliche Regel'],
    ['Null', 'Zahl ohne Wert'],
    ['Oger', 'Menschenfressender Riese'],
    ['Omen', 'Zeichen für die Zukunft'],
    ['Opal', 'Schillernder Schmuckstein'],
    ['Opus', 'Einzelnes Werk der Musik'],
    ['Orca', 'Schwarzweisser Wal'],
    ['Oval', 'Eiförmige Gestalt'],
    ['Peso', 'Währung in Lateinamerika'],
    ['Pils', 'Herbes helles Bier'],
    ['Poet', 'Verfasser von Versen'],
    ['Polo', 'Ballspiel zu Pferd'],
    ['Pony', 'Kleines Pferd, auch Frisur'],
    ['Popo', 'Hinterteil, kindlich'],
    ['Pose', 'Gestellte Haltung'],
    ['Pott', 'Grosser Topf, auch Schiff'],
    ['Prof', 'Hochschullehrer, kurz'],
    ['Pump', 'Kauf auf Kredit'],
    ['Punk', 'Laute Musik der Rebellen'],
    ['Pute', 'Weiblicher Truthahn'],
    ['Rage', 'Heftige Wut'],
    ['Reha', 'Kur nach der Krankheit'],
    ['Reiz', 'Anziehung, auch Sinnesimpuls'],
    ['Rind', 'Nutztier auf der Weide'],
    ['Riss', 'Spalt im Mauerwerk'],
    ['Rune', 'Zeichen der alten Germanen'],
    ['Ruin', 'Wirtschaftlicher Untergang'],
    ['Rute', 'Gerte des Anglers'],
    ['Saga', 'Erzählung aus dem Norden'],
    ['Same', 'Keimfähiges Korn der Pflanze'],
    ['Samt', 'Stoff mit weichem Flor'],
    ['Sarg', 'Letzte Truhe des Menschen'],
    ['Sari', 'Gewand der Inderin'],
    ['Shop', 'Laden auf Englisch'],
    ['Slum', 'Elendsviertel der Grossstadt'],
    ['Smog', 'Dunst über der Stadt'],
    ['Snob', 'Vornehm tuender Mensch'],
    ['Solo', 'Auftritt ganz allein'],
    ['Song', 'Lied der leichten Muse'],
    ['Sure', 'Abschnitt im Koran'],
    ['Talk', 'Gespräch im Fernsehen'],
    ['Tank', 'Behälter für Treibstoff'],
    ['Team', 'Gruppe mit gleichem Ziel'],
    ['Teen', 'Jugendlicher auf Englisch'],
    ['Test', 'Prüfung auf Tauglichkeit'],
    ['Tick', 'Kleine Eigenart'],
    ['Tide', 'Wechsel von Ebbe und Flut'],
    ['Tipi', 'Zelt der Prärieindianer'],
    ['Tofu', 'Quark aus Sojabohnen'],
    ['Toga', 'Gewand des alten Römers'],
    ['Tora', 'Heilige Schriftrolle'],
    ['Tour', 'Fahrt mit festem Ziel'],
    ['Tran', 'Öl aus Fischen'],
    ['Type', 'Buchstabe im Druck'],
    ['Unze', 'Gewicht für Gold'],
    ['Urin', 'Ausscheidung der Niere'],
    ['User', 'Nutzer eines Rechners'],
    ['Veto', 'Förmlicher Einspruch'],
    ['Vita', 'Lebenslauf auf Latein'],
    ['Vize', 'Zweiter in der Rangfolge'],
    ['Volt', 'Einheit der Spannung'],
    ['Wade', 'Muskel unter dem Knie'],
    ['Wurf', 'Weite Bewegung des Armes'],
    ['Yard', 'Englisches Längenmass'],
    ['Yeti', 'Schneemensch des Himalaja'],
    ['Yogi', 'Meister der Körperübungen'],
    ['Zehe', 'Glied am Fuss'],
    ['Zins', 'Preis für geliehenes Geld'],
    ['Zoff', 'Streit, umgangssprachlich'],
    ['Zone', 'Abgegrenzter Bereich']
  ]
}
