import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdBerge: Category = {
  id: "geografie",
  label: "Geografie",
  source: 'wikidata',
  entries: [
    ["Adwa", "Berg in Äthiopien"],
    ["Afdera", "Berg in Äthiopien"],
    ["Agung", "Berg in Indonesien"],
    ["Aju-Dag", "Berg in der Ukraine"],
    ["Ajusco", "Berg in Mexiko"],
    ["Ak-Kaya", "Historische Siedlung auf der Krim"],
    ["Albis", "Bergkette im Kanton Zürich"],
    ["Alcedo", "Berg in Ecuador"],
    ["Alid", "Berg in Eritrea"],
    ["Altmann", "Berg in der Schweiz"],
    ["Alvand", "Berg im Iran"],
    ["Ambae", "Berg in Vanuatu"],
    ["Amboto", "Berg in Spanien"],
    ["Ambrym", "Berg in Vanuatu"],
    ["Amiata", "Berg in Italien"],
    ["Aneto", "Höchster Berg der Pyrenäen"],
    ["Ankogel", "Berg in Österreich"],
    ["Api", "Berg in Nepal"],
    ["Apo", "Vulkan, höchste Berg der Philippinen"],
    ["Arafat", "Berg in Saudi-Arabien"],
    ["Aragaz", "Berg in Armenien"],
    ["Ararat", "Höchster Berg der Türkei"],
    ["Arenal", "Vulkan in Costa Rica"],
    ["Artos", "Berg in der Provinz Van, Türkei"],
    ["Athos", "Griechischer Berg"],
    ["Avala", "Berg in Serbien"],
    ["Ayelu", "Berg in Äthiopien"],
    ["Banahaw", "Berg auf den Philippinen"],
    ["Barkal", "Archäologischer Fundplatz im Sudan"],
    ["Barva", "Berg in Costa Rica"],
    ["Batu", "Berg in Äthiopien"],
    ["Batur", "Berg in Indonesien"],
    ["Baula", "Berg in Island"],
    ["Bazman", "Berg im Iran"],
    ["Bental", "Berg auf den Golanhöhen"],
    ["Bistra", "Berg bzw. Gebirge in Nordmazedonien"],
    ["Borawli", "Berg in Äthiopien"],
    ["Bristen", "Gipfel in den Glarner Alpen"],
    ["Bromo", "Vulkan auf Java, Indonesien"],
    ["Castor", "Gipfel in den Walliser Alpen"],
    ["Cauberg", "Berg in den Niederlanden"],
    ["Chiles", "Vulkan in Ecuador"],
    ["Chopok", "Berg in der Slowakei"],
    ["Cincar", "Berg in Bosnien und Herzegowina"],
    ["Civetta", "Berg in den Dolomiten"],
    ["Colima", "Vulkan in Mexiko"],
    ["Colo", "Berg in Indonesien"],
    ["Cumorah", "Berg in den USA"],
    ["Dajti", "Berg in Albanien"],
    ["Dallol", "Geothermalgebiet in Äthiopien"],
    ["Darwin", "Berg in Ecuador"],
    ["Denali", "Höchster Berg Nordamerikas"],
    ["Diran", "Berg in Pakistan"],
    ["Ebal", "Berg im Staat Palästina"],
    ["Eiger", "Gipfel in den Berner Alpen"],
    ["Elba", "Berg in Ägypten"],
    ["Elbrus", "Höchster Berg im Kaukasus"],
    ["Errigal", "Berg in Irland"],
    ["Esja", "Gebirgszug im Südwesten Islands"],
    ["Falknis", "Berg in den Alpen"],
    ["First", "Berg in den Alpen in der Schweiz"],
    ["Fischt", "Berg im Kaukasus"],
    ["Fuji", "Berg in Japan"],
    ["Gahinga", "Berg in Ruanda"],
    ["Galeras", "Berg in Kolumbien"],
    ["Garizim", "Berg in Palästina"],
    ["Girnar", "Berg in Indien"],
    ["Gollak", "Berg in Serbien"],
    ["Grammos", "Berg in Albanien"],
    ["Gridone", "Berg in den Alpen"],
    ["Grivola", "Zweithöchste Berg der Grajischen Alpen"],
    ["Guaita", "Felsmassiv in San Marino-Stadt"],
    ["Hajla", "Berg in Kosovo"],
    ["Hakone", "Gebirge in Japan"],
    ["Haraz", "Berg im Jemen"],
    ["Hegau", "Berg in Deutschland"],
    ["Hermon", "Berg in Israelisch besetzte Gebiete"],
    ["Hochtor", "Berg in Österreich"],
    ["Howerla", "Berg in der Ukraine"],
    ["Ibu", "Vulkan in Indonesien"],
    ["Ikoma", "Berg in Japan"],
    ["Iraya", "Berg auf den Philippinen"],
    ["Iremel", "Berg im Ural"],
    ["Isarog", "Berg auf den Philippinen"],
    ["Ithomi", "Berg in Griechenland"],
    ["Iti", "Berg in Griechenland"],
    ["Iwaki", "Berg in Japan"],
    ["Iwate", "Berg in Japan"],
    ["Kadovar", "Berg in Papua-Neuguinea"],
    ["Kangto", "Berg in Indien"],
    ["Kanlaon", "Schichtvulkan auf den Philippinen"],
    ["Kao", "Insel in Tonga"],
    ["Karkar", "Vulkaninsel in Papua-Neuguinea"],
    ["Kasbek", "Berg in Russland"],
    ["Kelut", "Vulkan in Indonesien"],
    ["Kinyeti", "Berg in Südsudan"],
    ["Kjerag", "Berg in Norwegen"],
    ["Klabat", "Schichtvulkan in Indonesien"],
    ["Koli", "Berg in Finnland"],
    ["Kongur", "Berg in der Volksrepublik China"],
    ["Korab", "Berg in Albanien und Nordmazedonien"],
    ["Kosmaj", "Berg in Serbien"],
    ["Krafla", "Vulkansystem im Norden Islands"],
    ["Kupe", "Schichtvulkan in Kamerun"],
    ["Kuwohi", "Berg in den Appalachen"],
    ["Kynthos", "Berg in Griechenland"],
    ["Lhotse", "Berg im Himalaya"],
    ["Linzor", "Berg in Bolivien"],
    ["Llaima", "Berg in Chile"],
    ["Lokon", "Berg in Indonesien"],
    ["Loreley", "Felswand am Mittelrhein"],
    ["Mafadi", "Berg in Lesotho"],
    ["Makalu", "Berg in Volksrepublik China"],
    ["Manam", "Insel in Papua-Neuguinea"],
    ["Manaslu", "Berg in Nepal"],
    ["Marjan", "Berg in Split, Kroatien"],
    ["Mayon", "Vulkan auf den Philippinen"],
    ["Merbabu", "Berg in Indonesien"],
    ["Meru", "Berg in Indien"],
    ["Mikeno", "Berg in dem Kongo"],
    ["Musala", "Berg in Bulgarien"],
    ["Mustau", "Berg in der Volksrepublik China"],
    ["Nabro", "Berg in Eritrea"],
    ["Namsan", "Südkoreanischer Berg in Seoul"],
    ["Nebo", "Religiös bedeutsamer Berg in Jordanien"],
    ["Negoiu", "Berg in Rumänien"],
    ["Nemo", "Berg in Russland"],
    ["Ngaoui", "Berg in Kamerun"],
    ["Ngozi", "Berg in Tansania"],
    ["Niesen", "Berg im Berner Oberland"],
    ["Noshak", "Berg in Afghanistan"],
    ["Nuptse", "Berg im Himalaya"],
    ["Ölberg", "Berg in Israel"],
    ["Olympos", "Höchster Berg auf der Insel Zypern"],
    ["Orhi", "Berg in den Pyrenäen"],
    ["Othrys", "Gebirgszug in Griechenland"],
    ["Pacaya", "Berg in Guatemala"],
    ["Papuk", "Berg in Kroatien"],
    ["Parnass", "Berg in Griechenland"],
    ["Pendeli", "Berg in Griechenland"],
    ["Petros", "Berg in der Ukraine"],
    ["Pikuj", "Berg in der Ukraine"],
    ["Pilatus", "Bergmassiv in der Zentralschweiz"],
    ["Pisco", "Berg in Peru"],
    ["Pitons", "Berg auf St. Lucia"],
    ["Pobeda", "Berg im Tscherskigebirge"],
    ["Pollux", "Gipfel in den Walliser Alpen"],
    ["Porak", "Berg in Aserbaidschan"],
    ["Prenj", "Gebirge in Bosnien und Herzegowina"],
    ["Psunj", "Berg in Kroatien"],
    ["Puigmal", "Berg in den Pyrenäen"],
    ["Pulag", "Berg auf den Philippinen"],
    ["Pumori", "Berg in Volksrepublik China"],
    ["Putana", "Berg in Bolivien"],
    ["Puyehue", "Vulkan in den südchilenischen Anden"],
    ["Razor", "Berg in Slowenien"],
    ["Rigi", "Bergmassiv in der Zentralschweiz"],
    ["Rinjani", "Schichtvulkan in Indonesien"],
    ["Rogla", "Berg in Slowenien"],
    ["Ruj", "Berg in Bulgarien"],
    ["Rungwe", "Berg in Tansania"],
    ["Rysy", "Berg in Polen und der Slowakei"],
    ["Saana", "Berg in Finnland"],
    ["Sabalan", "Berg im Iran"],
    ["Sangay", "Vulkan in Ecuador"],
    ["Säntis", "Berg im Alpstein (Ostschweiz)"],
    ["Semnoz", "Berg in Frankreich"],
    ["Serles", "Berg in Tirol"],
    ["Sinai", "Berg in Ägypten"],
    ["Skopus", "Berg in Israel"],
    ["Slamet", "Berg in Indonesien"],
    ["Soira", "Berg in Eritrea"],
    ["Storen", "Berg in Norwegen"],
    ["Taapaca", "Berg in Chile"],
    ["Tacora", "Berg in Chile"],
    ["Tafahi", "Tongaische Insel"],
    ["Taftan", "Berg im Iran"],
    ["Tahat", "Berg in Algerien"],
    ["Tambora", "Vulkan in Indonesien"],
    ["Tepeyac", "Berg in Mexiko"],
    ["Titano", "Berg im Apennin"],
    ["Titlis", "Berg der Urner Alpen, Schweiz"],
    ["Tödi", "Höchster Gipfel der Glarner Alpen"],
    ["Tofua", "Berg in Tonga"],
    ["Torre", "Berg in Portugal"],
    ["Triglav", "Höchster Berg Sloweniens"],
    ["Trishul", "Berg in Indien"],
    ["Trivor", "Berg in Pakistan"],
    ["Tromen", "Ein Vulkan"],
    ["Tubqal", "Berg in Marokko"],
    ["Uhud", "Berg in Saudi-Arabien"],
    ["Umboi", "Berg in Papua-Neuguinea"],
    ["Urgull", "Berg in Spanien"],
    ["Uschba", "Berg in Georgien"],
    ["Viedma", "Berg in Argentinien"],
    ["Visoke", "Berg in dem Kongo"],
    ["Vodno", "Berg in Nordmazedonien"],
    ["Vran", "Berg in Bosnien und Herzegowina"],
    ["Vulcano", "Berg in Italien"],
    ["Xueshan", "Berg in Taiwan"]
  ]
}
