import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdBerufe: Category = {
  id: "menschSprache",
  label: "Mensch & Sprache",
  source: 'wikidata',
  entries: [
    ["Agronom", "Fachperson für Landwirtschaft"],
    ["Almosenier", "Kirchlicher Armenpfleger, Amtsträger"],
    ["Ama", "Japanische Muscheltaucherinnen"],
    ["Angestellter", "Person, die geistig arbeitet"],
    ["Animator", "Person, die Animationsfilme herstellt"],
    ["Apparatschik", "Beruf"],
    ["Aufwecker", "Historischer Beruf"],
    ["Bauarbeiter", "Arbeiter auf einem Bau"],
    ["Boxer", "Person, die den Boxsport ausübt"],
    ["Busfahrer", "Beruf; Person, die einen Omnibus fährt"],
    ["Bushi", "Japanischer Krieger"],
    ["Cembalist", "Musiker auf dem Cembalo"],
    ["Chorleiter", "Person, die einen Chor leitet"],
    ["Chronist", "Person, die Chroniken schreibt"],
    ["Condottiere", "Söldnerführer in Italien"],
    ["Connaisseur", "Kenner eines Kulturaspekts"],
    ["Croupier", "Mitarbeiter einer Spielbank"],
    ["Devadasi", "Indische Tempeldienerinnen"],
    ["Doula", "Nichtmedizinische Helferin"],
    ["Entomologe", "Zoologe, der sich mit Insekten befasst"],
    ["Erzieher", "Pädagogische Fachkraft"],
    ["Essayist", "Person, die Essays verfasst"],
    ["Fischer", "Person, die den Fischfang ausübt"],
    ["Flibustier", "Kaperfahrer, imperialistischer Agent"],
    ["Fotojournalist", "Fotograf für Pressemedien"],
    ["Geldwechsler", "Kaufmännischer Beruf"],
    ["Glaser", "Handwerker, der Glas verarbeitet"],
    ["Goldschmied", "Beruf"],
    ["Graveur", "Person, die Gravuren anfertigt"],
    ["Grid-Girl", "Hostess während einer Startaufstellung"],
    ["Griot", "Sänger, Rezitator und Erzähler"],
    ["Gutsherr", "Historische Herrschaftsform"],
    ["Hafenkapitän", "Amtsperson im Hafen"],
    ["Häresiarch", "Anführer einer Sekte"],
    ["Haushofmeister", "Leiter der Hausangestellten"],
    ["Hausierer", "Von Haus zu Haus gehender Händler"],
    ["Heilkundler", "Beruf in der Alternativmedizin"],
    ["Historiker", "Beruf"],
    ["Hofdame", "Bestandteil eines Hofstaates"],
    ["Hofmaler", "Maler in einem Hofstaat"],
    ["Hofmeister", "Oberstes Hofamt"],
    ["Hotelmanager", "Person, der ein Hotel leitet"],
    ["Illustrator", "Person, die Druckerzeugnisse bebildert"],
    ["Imitator", "Person, die andere Personen nachahmt"],
    ["Jockey", "Berufsmäßiger Pferderennreiter"],
    ["Kadi", "Islamischer Rechtsgelehrter, Richter"],
    ["Keyboarder", "Musiker, der Keyboard spielt"],
    ["Kolumnist", "Verfasser von Kolumnen"],
    ["Korrektor", "Beruf"],
    ["Korsar", "Beruf"],
    ["Kunoichi", "Weibliche Ninja"],
    ["Laborant", "Fachkraft in einem Labor"],
    ["Librettist", "Autor des Librettos einer Oper"],
    ["Logopäde", "Spezialist in der Sprachheilkunde"],
    ["Mangaka", "Personen, die Mangas zeichnen"],
    ["Marshaller", "Bodenlotse an Flughäfen"],
    ["Meddah", "Türkische Vortragskünstler"],
    ["Melamed", "Lehrer im Judentum"],
    ["Milchmädchen", "Mädchen oder Frau zum Melken von Kühen"],
    ["Milchmann", "Person, die Milch liefert"],
    ["Muezzin", "Ausrufer, der Muslime zum Gebet ruft"],
    ["Muhtasib", "Person, die die Hisba ausübt"],
    ["Oshiya", "Personal der Tokioter U-Bahn"],
    ["Parfümeur", "Beruf zur Kreation von Parfüm"],
    ["Patissier", "Konditor in einer Küchenbrigade"],
    ["Picador", "Berittener Stierkämpfer"],
    ["Pionierte", "Truppengattung eines Heeres"],
    ["Podcaster", "Person, die Podcasts herstellt"],
    ["Präfekt", "Beruf"],
    ["Produzent", "Medien- und Unterhaltungsberuf"],
    ["Prosaist", "Autor von Prosa"],
    ["Psychiater", "Beruf"],
    ["Rabbiner", "Jüdischer Religionsgelehrter"],
    ["Radrennfahrer", "Person, die Rennradsport betreibt"],
    ["Ranger", "Wald- und Wildhüter"],
    ["Regentschaft", "Vertretung des Monarchen"],
    ["Requisiteur", "Film- und Theaterberuf"],
    ["Rezeptionist", "Beschäftigter am Empfang"],
    ["Roadie", "Mitreisender Veranstaltungstechniker"],
    ["Romancier", "Autor von Romanen"],
    ["Sänger", "Person, die singt"],
    ["Sattler", "Lederwaren herstellende Person"],
    ["Scharfschütze", "Beruf"],
    ["Schatzmeister", "Person im Vorstand einer Gesellschaft"],
    ["Sekretär", "Beruf im Bürowesen"],
    ["Seneschall", "Feudal höfisches Amt im Mittelalter"],
    ["Showgirl", "Tänzerin oder Unterhaltungskünstlerin"],
    ["Skalde", "Skandinavischer Hofdichter"],
    ["Sofer", "Schreiber oder Schriftgelehrter"],
    ["Sommelier", "Berater und Gutachter für Wein"],
    ["Songschreiber", "Person, die Songs verfasst"],
    ["Spin-Doctor", "Medien- oder Image-Berater"],
    ["Sportmanager", "Beruf im professionellen Sport"],
    ["Stadtplaner", "Beschäftigt sich mit der Stadtplanung"],
    ["Strongman", "Typ von Kraftsportler"],
    ["Superintendent", "Kirchliches Amt"],
    ["Supervision", "Beratungsform für Mitarbeiter"],
    ["Szenenbildner", "Beruf im Filmgewerbe"],
    ["Szenograf", "Beruf in der Theater- und Filmbranche"],
    ["Tagelöhner", "Person, die tageweise arbeitet"],
    ["Tarento", "Japanischer Entertainer"],
    ["Taxifahrer", "Fahrer eines Taxis"],
    ["Telefonist", "Mitarbeiter im Fernsprechverkehr"],
    ["Tennisspieler", "Person, die Tennis spielt"],
    ["Testpilot", "Speziell geschulter Pilot"],
    ["Töpfer", "Handwerklicher Beruf"],
    ["Totengräber", "Person, die Tote begräbt"],
    ["Trobairitz", "Okzitanische Troubadourin"],
    ["Tycoon", "Großindustrieller, Magnat oder Mogule"],
    ["Umpire", "Schiedsrichter im Cricketsport"],
    ["Verkäufer", "Beruf, etwas zu verkaufen"],
    ["Video-Blogger", "Art von Blogger"],
    ["Vigilante", "Systemstabilisierende Selbstjustiz"],
    ["Volkskundler", "Person, die Folklore studiert"],
    ["Vorgesetzter", "Berufliche Position in Organisationen"],
    ["Wachmann", "Person employed to protect assets"],
    ["Waldläufer", "Pelzhändler im kolonialen Nordamerika"],
    ["Wäscherin", "Frau, die Wäsche wäscht"],
    ["Werbetexter", "Verfasser von Werbetexten"],
    ["Zeichner", "Person, die zeichnet"]
  ]
}
