import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdEssen: Category = {
  id: "alltag",
  label: "Alltag & Essen",
  source: 'wikidata',
  entries: [
    ["Affenhirn", "Gehirn eines Affen"],
    ["Agliata", "Italienische Knoblauchsoße"],
    ["Amarula", "Spirituosenmarke aus Südafrika"],
    ["Aperitif", "Meist alkoholisches Getränk"],
    ["Aquavit", "Gewürzter Branntwein"],
    ["Arak", "Orientalischer Anisschnaps"],
    ["Aspik", "Gelee aus Fleisch oder Fisch"],
    ["Atole", "Mittelamerikanisches Heißgetränk"],
    ["Aviation", "Cocktail mit Gin"],
    ["Baileys", "Markenname eines irischen Sahnelikörs"],
    ["Baklava", "Schichtgebäck aus dem Nahen Osten"],
    ["Bakso", "Gericht der indonesischen Küche"],
    ["Ballokume", "Traditionelles albanisches Süßgebäck"],
    ["Bami", "Nudelgericht aus Indonesien"],
    ["Beaujolais", "Französisches Weinbaugebiet"],
    ["Beondegi", "Koreanisches Imbissgericht"],
    ["Berliner", "Siedegebäck aus süßem Hefeteig"],
    ["Bigos", "Speise oder Getränk"],
    ["Bingsu", "Koreanisches Dessert"],
    ["Biryani", "Asiatisches Reisgericht"],
    ["Bismarckhering", "Eingelegte marinierte Heringslappen"],
    ["Blutwurst", "Speise oder Getränk"],
    ["Bobotie", "Südafrikanischer Hackbraten"],
    ["Börek", "Herzhaft gefülltes Strudelteiggebäck"],
    ["Bosbasch", "Suppe in der Aserbaidschanischen Küche"],
    ["Bouillabaisse", "Fischsuppe der provenzalischen Küche"],
    ["Brimsennocken", "Slowakisches Nationalgericht"],
    ["Cachupa", "Traditionelles Gericht von Kap Verde"],
    ["Caesar", "Kanadischer Cocktail"],
    ["Caipirinha", "Aus Brasilien stammender Cocktail"],
    ["Calpis", "Japanisches Unternehmen"],
    ["Caprese", "Italienischer Vorspeisensalat"],
    ["Ceviche", "Peruanisches Fischgericht"],
    ["Chakalaka", "Afrikanische Würzsauce"],
    ["Chawanmushi", "Japanisches Gericht"],
    ["Chips", "Speise oder Getränk"],
    ["Chokladboll", "Schwedische Backwarenspezialität"],
    ["Cobbler", "Amerikanische/Britische Süßspeise"],
    ["Corona", "Mexikanische Biermarke"],
    ["Cosmopolitan", "Cocktail mit Cointreau"],
    ["Crostini", "Gericht der italienischen Küche"],
    ["Dakos", "Vorspeise der griechischen Küche"],
    ["Dalgona", "Koreanische Süßigkeit"],
    ["Dasani", "Tafelwasser der Coca-Cola Company"],
    ["Dondurma", "Türkische Bezeichnung für Speiseeis"],
    ["Duxelles", "Masse aus fein gehackten Pilzen"],
    ["Empanada", "Gefüllte Teigtasche"],
    ["Fabada", "Spanisches Bohnengericht, Eintopf"],
    ["Falafel", "Speise oder Getränk"],
    ["Farofa", "Geröstetes Maniokmehl"],
    ["Fleischpastete", "Pastete mit einer Füllung aus Fleisch"],
    ["Gado-gado", "Gericht in Indonesien"],
    ["Gimbap", "Koreanisches Gericht"],
    ["Grasgelee", "Traditionelles chinesisches Dessert"],
    ["Gudeg", "Gericht aus Java"],
    ["Harira", "Suppe der nordafrikanischen Küche"],
    ["Hwajeon", "Traditionelle koreanische Speise"],
    ["Ikizukuri", "Sashimivariante der japanischen Küche"],
    ["Jameson", "Irische Whiskey-Marke"],
    ["Japchae", "Koreanische Nudelspeise"],
    ["Jupiler", "Belgische Biermarke"],
    ["Kartoffelsalat", "Speise oder Getränk"],
    ["Kilkenny", "Irisches, rotes Ale"],
    ["Kir", "Cocktail mit Crème de Cassis"],
    ["Knoblauchsuppe", "Suppe mit Knoblauch"],
    ["Kumys", "Vergorene Stutenmilch"],
    ["Kuschari", "Ägyptisches Gericht"],
    ["Laksa", "Südostasiatische Suppe"],
    ["Lassi", "Südasiatisches Joghurtgetränk"],
    ["Leffe", "Belgisches Abteibier"],
    ["Lemang", "Reisgericht Indonesia"],
    ["Linsensuppe", "Suppe aus Linsen"],
    ["Lohikeitto", "Finnische Fischsuppe"],
    ["Lokum", "Süßware osmanischer Herkunft"],
    ["Lontong", "Gericht in Indonesien"],
    ["Maistee", "Koreanischer Tee aus Mais"],
    ["Mandelmilch", "Pflanzenmilch aus Mandeln"],
    ["Mandu", "Gefüllte Teigtaschen aus Korea"],
    ["Manhattan", "Cocktail mit Whiskey"],
    ["Margarita", "Cocktail mit Tequila"],
    ["Martini", "Cocktail mit Wermut"],
    ["Menemen", "Türkische Eierspeise mit Tomaten"],
    ["Merlot", "Italienische Rebsorte"],
    ["Mille-feuille", "Französischer Blätterteigkuchen"],
    ["Mimosa", "Cocktail mit Champagner"],
    ["Moules-frites", "Speisen aus Muscheln und Pommes frites"],
    ["Mousakas", "Speise oder Getränk"],
    ["Muhallebi", "Iranisches Dessert"],
    ["Nudelsalat", "Salat mit Nudeln"],
    ["Ochsenschwanz", "Scheiben vom Rinderschwanz mit Knochen"],
    ["Orval", "Belgisches Trappistenbier"],
    ["Oyakodon", "Japanisches Gericht"],
    ["Paella", "Reisgericht aus der Region Valencia"],
    ["Palmwein", "Alkoholisches Getränk"],
    ["Panipuri", "Indischer Snack"],
    ["Panzanella", "Italienischer Salat"],
    ["Papadam", "Frittiertes Fladenbrot aus Bohnenmehl"],
    ["Paprikasch", "Ungarische Nationalgericht"],
    ["Piperade", "Traditionelles baskisches Gericht"],
    ["Poke", "Hawaiisches Nationalgericht"],
    ["Pombe", "Biersorten aus Ostafrika"],
    ["Popcorn", "Nahrungsmittel aus Mais"],
    ["Poutine", "Kanadische Fast-Food-Spezialität"],
    ["Queimada", "Brauch der galicischen Küche"],
    ["Rakija", "Alkoholisches Getränk"],
    ["Retsina", "Mit Harz versetzter griechischer Wein"],
    ["Roastbeef", "Speise oder Getränk"],
    ["Rousong", "Getrocknetes Fleischprodukt"],
    ["Rujak", "Traditioneller javanischer Salat"],
    ["Saganaki", "Gebratener griechischer Käse"],
    ["Sahti", "Finnisches Wacholderbier"],
    ["Sambuca", "Italienischer Anislikör"],
    ["Samosa", "Indische Teigtaschen"],
    ["Schwarte", "Haut vom Schwein"],
    ["Screwdriver", "Longdrink aus Orangensaft und Wodka"],
    ["Shakshuka", "Eierspeise mit Tomaten"],
    ["Sidecar", "Cocktail mit Cognac"],
    ["Sikhye", "Süßes Reisgetränk aus Korea"],
    ["Singha", "Thailändische Biermarke"],
    ["Skordalia", "Griechisches Dip oder Vorspeise"],
    ["Soju", "Alkoholisches Getränk aus Korea"],
    ["Sommerrolle", "Vorspeise der vietnamesischen Küche"],
    ["Sportgetränk", "Art von Funktionsgetränk"],
    ["Spritz", "Cocktail mit Sodawasser"],
    ["Stolichnaya", "Russischer Wodka"],
    ["Stracciatella", "Italienisches Suppengericht"],
    ["Struffoli", "Italienisches Siedegebäck in Honig"],
    ["Surströmming", "Schwedische Fischspeise"],
    ["Tahchin", "Iranisches Reisgericht"],
    ["Tako-yaki", "Japanischer Teig-Snack mit Oktopusarm"],
    ["Tamale", "Lateinamerikanisches Gericht"],
    ["Tanqueray", "Britische Gin-Marke"],
    ["Tatar", "Fleischzubereitung vom Rind"],
    ["Tepache", "Mexikanisches Getränk"],
    ["Thieboudienne", "Nationalgericht des Senegal"],
    ["Tiger-Bier", "Asiatische Biermarke aus Singapur"],
    ["Tomatensuppe", "Suppe aus Tomaten"],
    ["Toum", "Libanesische Knoblauchcreme"],
    ["Trepang", "Zubereitung aus Seegurken"],
    ["Tsoureki", "Griechischer Hefekopf"],
    ["Tteokbokki", "Koreanisches Gericht"],
    ["Ugali", "Getreidebrei aus Maismehl in Afrika"],
    ["Unadon", "Gericht in Japan"],
    ["Unterschenkel", "Teil des Beines zwischen Knie und Fuß"],
    ["Waldorfsalat", "Amerikanischer Salat"],
    ["Watruschka", "Osteuropäisches Süßgebäck"],
    ["Wermut", "Alkoholisches Getränk"],
    ["Yakiniku", "Japanische Art Fleisch zu grillen"],
    ["Zabaglione", "Italienische Nachspeise"],
    ["Zimmes", "Gericht aus der jüdischen Küche"],
    ["Zimtschnecke", "Skandinavische Backwarenspezialität"],
    ["Zuccotto", "Italienische Süßspeise"],
    ["Zuckerei", "Dessert und Cocktail"],
    ["Zuckerrohrsaft", "Saft aus Zuckerrohr"],
    ["Zwiebelringe", "Speise oder Getränk"]
  ]
}
