import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdFluesse: Category = {
  id: "geografie",
  label: "Geografie",
  source: 'wikidata',
  entries: [
    ["Aare", "Fluss in der Schweiz"],
    ["Abava", "Nebenfluss der Venta"],
    ["Abens", "Nebenfluss der Donau"],
    ["Abra", "Fluss auf den Philippinen"],
    ["Adaja", "Fluss in Spanien"],
    ["Adda", "Fluss in Italien"],
    ["Adswa", "Nebenfluss der Ussa"],
    ["Aff", "Nebenfluss des Ousts"],
    ["Ahja", "Fluss in Estland"],
    ["Ahr", "Linker Nebenfluss des Mittelrheins"],
    ["Ain", "Fluss in Frankreich"],
    ["Aisne", "Fluss in Frankreich"],
    ["Aksu", "Fluss in Kirgisistan"],
    ["Alle", "Fluss in Polen"],
    ["Alz", "Fluss in Bayern"],
    ["Amel", "Fluss in Belgien, mündet in Ourthe"],
    ["Amer", "Fluss in den Niederlanden"],
    ["Amur", "Strom in China und Russland"],
    ["Ancre", "Nebenfluss der Somme"],
    ["Annan", "Fluss im Vereinigten Königreich"],
    ["Aras", "Fluss in Armenien"],
    ["Arda", "Nebenfluss der Mariza"],
    ["Argun", "Fluss in Volksrepublik China"],
    ["Arly", "Fluss in Frankreich"],
    ["Arpa", "Fluss in Aserbaidschan"],
    ["Arun", "Fluss im Vereinigten Königreich"],
    ["Assa", "Fluss in Georgien und Russland"],
    ["Atrak", "Fluss in Turkmenistan"],
    ["Aulne", "Fluss in Frankreich"],
    ["Avon", "Fluss in England mit Mündung im Severn"],
    ["Avre", "Nebenfluss der Eure"],
    ["Bani", "Rechter Nebenfluss des Niger in Mali"],
    ["Baro", "Fluss in Südsudan"],
    ["Beas", "Fluss in Indien"],
    ["Bega", "Nebenfluss der Theiß"],
    ["Benue", "Fluss in Nigeria"],
    ["Bille", "Nebenfluss der Elbe"],
    ["Birs", "Fluss in der Schweiz"],
    ["Blees", "Fluss in Luxemburg"],
    ["Bober", "Nebenfluss der Oder"],
    ["Bode", "Nebenfluss der Saale"],
    ["Breg", "Quellfluss der Donau"],
    ["Brenz", "Nebenfluss der Donau"],
    ["Buna", "Fluss in Albanien"],
    ["Clyde", "Fluss in Schottland"],
    ["Dawa", "Fluss in Äthiopien"],
    ["Dee", "Fluss im Vereinigten Königreich"],
    ["Deima", "Mündungsarm des Pregels"],
    ["Desna", "Fluss in der Ukraine"],
    ["Dez", "Fluss in dem Iran"],
    ["Dja", "Fluss in Kamerun"],
    ["Dore", "Nebenfluss des Alliers"],
    ["Doubs", "Fluss in der Schweiz"],
    ["Douro", "Fluss auf der iberischen Halbinsel"],
    ["Drau", "Fluss in Slowenien"],
    ["Drin", "Fluss in Albanien"],
    ["Drut", "Rechter Nebenfluss de Dnepr"],
    ["Düna", "Fluss in Belarus"],
    ["Eem", "Fluss in den Niederlanden"],
    ["Eger", "Fluss in Tschechien"],
    ["Elz", "Nebenfluss des Rheins"],
    ["Emba", "Fluss in Kasachstan"],
    ["Emme", "Nebenfluss der Aare"],
    ["Enz", "Fluss in Deutschland"],
    ["Epte", "Rechter Nebenfluss der Seine"],
    ["Erne", "Fluss im Vereinigten Königreich"],
    ["Erzen", "Fluss in Albanien"],
    ["Esk", "Fluss in England"],
    ["Esla", "Fluss in Spanien"],
    ["Etsch", "Fluss in Italien"],
    ["Eure", "Fluss im Nordwesten Frankreichs"],
    ["Fils", "Nebenfluss des Neckars"],
    ["Fly", "Fluss in Papua-Neuguinea"],
    ["Forth", "Fluss in Schottland"],
    ["Gail", "Nebenfluss der Drau"],
    ["Gauja", "Fluss in Lettland und Estland"],
    ["Geba", "Fluss in Senegal"],
    ["Gera", "Nebenfluss der Unstrut"],
    ["Gers", "Nebenfluss der Garonne"],
    ["Glan", "Nebenfluss der Gurk"],
    ["Gomal", "Fluss in Pakistan"],
    ["Gunt", "Fluss in Tadschikistan"],
    ["Gurk", "Nebenfluss der Drau in Kärnten"],
    ["Gwda", "Nebenfluss der Netze"],
    ["Hamme", "Nebenfluss der Lesum in Niedersachsen"],
    ["Haro", "Fluss in Pakistan"],
    ["Havel", "Rechter Nebenfluss der Elbe"],
    ["Hotan", "Fluss in der Volksrepublik China"],
    ["Hugli", "Fluss in Westbengalen, Indien"],
    ["Hull", "Fluss in England"],
    ["Ider", "Fluss in der Mongolei"],
    ["Ilek", "Nebenfluss des Ural"],
    ["Ilet", "Nebenfluss der Wolga"],
    ["Ili", "Fluss in Kasachstan"],
    ["Ill", "Fluss in Österreich"],
    ["Ille", "Nebenfluss der Vilaine"],
    ["Iller", "Rechter Nebenfluss der Donau"],
    ["Ilova", "Fluss in Kroatien"],
    ["Ilz", "Fluss in Deutschland"],
    ["Imjin", "Koreanischer Fluss"],
    ["Ina", "Nebenfluss der Oder"],
    ["Indus", "Fluss in Volksrepublik China"],
    ["Inhul", "Fluss in der Ukraine"],
    ["Iori", "Fluss in Georgien und Aserbaidschan"],
    ["Isle", "Nebenfluss der Dordogne"],
    ["Iton", "Nebenfluss der Eure"],
    ["Iza", "Nebenfluss der Theiß"],
    ["Juba", "Fluss in Somalia"],
    ["Kafue", "Fluss in Sambia"],
    ["Kaidu", "Fluss in China"],
    ["Kamo", "Fluss in Japan"],
    ["Kamp", "Nebenfluss der Donau"],
    ["Klang", "Fluss in Malaysia"],
    ["Kok", "Fluss in Thailand"],
    ["Kolp", "Nebenfluss der Suda"],
    ["Kolwa", "Fluss im europäischen Teil Russlands"],
    ["Konqi", "Fluss in der Volksrepublik China"],
    ["Kotui", "Fluss im Norden Sibirens"],
    ["Krka", "Nebenfluss der Save"],
    ["Kuban", "Fluss in Russland"],
    ["Kuma", "Zufluss des Kaspischen Meeres"],
    ["Kunar", "Fluss in Pakistan und Afghanistan"],
    ["Kunda", "Fluss in Estland"],
    ["Kupa", "Fluss in Slowenien"],
    ["Kura", "Fluss in Transkaukasien"],
    ["Kvina", "Fluss in Norwegen"],
    ["Kyll", "Nebenfluss der Mosel"],
    ["Lea", "Fluss in England"],
    ["Leie", "Nebenfluss der Schelde"],
    ["Lena", "Strom zur Leptewsee in Russland"],
    ["Lesse", "Fluss in Belgien, mündet in Maas"],
    ["Lim", "Nebenfluss der Drina"],
    ["Linth", "Fluss in der Schweiz"],
    ["Liri", "Italienischer Fluss"],
    ["Loir", "Nebenfluss der Sarthe"],
    ["Lol", "Fluss im Südsudan"],
    ["Loue", "Nebenfluss des Doubs"],
    ["Luga", "Fluss in Russland"],
    ["Luni", "Fluss in Indien"],
    ["Lusa", "Nebenfluss des Jugs"],
    ["Maas", "Fluss in den Niederlanden"],
    ["Mano", "Fluss in Guinea"],
    ["Mara", "Fluss in Ostafrika"],
    ["Marne", "Nebenfluss der Seine"],
    ["Mbam", "Fluss in Kamerun"],
    ["Memel", "Fluss in Litauen"],
    ["Mies", "Nebenfluss der Berounka"],
    ["Moei", "Fluss in Thailand"],
    ["Mono", "Längster Fluss Togos"],
    ["Mun", "Fluss in Thailand"],
    ["Mur", "Nebenfluss der Drau"],
    ["Murr", "Nebenfluss des Neckars"],
    ["Musi", "Fluss in Indonesien"],
    ["Nadym", "Fluss in Russland"],
    ["Naf", "Fluss in Bangladesch und in Myanmar"],
    ["Nahe", "Linker Nebenfluss des Rheins"],
    ["Nara", "Linker Nebenfluss der Oka in Russland"],
    ["Narew", "Fluss in Polen"],
    ["Nene", "Fluss in England"],
    ["Ner", "Nebenfluss der Warthe"],
    ["Neris", "Fluss in Litauen und Belarus"],
    ["Ness", "Fluss im Vereinigten Königreich"],
    ["Netze", "Nebenfluss der Warthe"],
    ["Nida", "Nebenfluss der Weichsel in Polen"],
    ["Nied", "Nebenfluss der Saar"],
    ["Niers", "Nebenfluss der Maas"],
    ["Niger", "Strom in Afrika"],
    ["Nitra", "Nebenfluss der Waag"],
    ["Nive", "Nebenfluss des Adours"],
    ["Obal", "Fluss in Belarus"],
    ["Obra", "Nebenfluss der Warthe"],
    ["Odon", "Nebenfluss der Orne"],
    ["Ognon", "Nebenfluss der Saône"],
    ["Ogre", "Nebenfluss der Düna"],
    ["Ohre", "Nebenfluss der Elbe"],
    ["Oise", "Nebenfluss der Seine in der Picardie"],
    ["Oka", "Fluss mit Mündung im Bratsker Stausee"],
    ["Oker", "Nebenfluss der Aller"],
    ["Olsa", "Nebenfluss der Oder"],
    ["Olt", "Nebenfluss der Donau in Rumänien"],
    ["Onon", "Fluss in Ostasien"],
    ["Orbe", "Fluss in Frankreich und der Schweiz"],
    ["Ossam", "Nebenfluss der Donau"],
    ["Osum", "Fluss in Albanien"],
    ["Osun", "Fluss im Südwesten Nigerias"],
    ["Oti", "Westafrikanischer Fluss"],
    ["Otra", "Fluss in Norwegen"],
    ["Our", "Nebenfluss der Sauer"],
    ["Ouse", "Fluss in Yorkshire, England"],
    ["Oust", "Nebenfluss der Vilaine"],
    ["Palar", "Fluss in Indien"],
    ["Pamir", "Fluss in Tadschikistan"],
    ["Peene", "Mitteleuropäischer Fluss zur Ostsee"],
    ["Pek", "Fluss in Serbien"],
    ["Pina", "Linker Nebenfluss des Prypjats"],
    ["Pissa", "Nebenfluss der Angrapa"],
    ["Piva", "Nebenfluss der Drina"],
    ["Pivka", "Fluss in Slowenien"],
    ["Pra", "Fluss in Ghana"],
    ["Queis", "Fluss in Polen"],
    ["Raba", "Nebenfluss der Weichsel"],
    ["Ramu", "Fluss in Papua-Neuguinea"],
    ["Rauma", "Fluss in Norwegen"],
    ["Ravi", "Fluss in Indien und Pakistan"],
    ["Rhone", "Fluss in der Schweiz"],
    ["Rienz", "Fluss in Italien"],
    ["Rioni", "Fluss in Georgien"],
    ["Risle", "Nebenfluss der Seine"],
    ["Rott", "Niederbayerischer Fluss"],
    ["Ruhr", "Fluss in Deutschland"],
    ["Rur", "Rechter Nebenfluss der Maas"],
    ["Ryck", "Fluss in Mecklenburg-Vorpommern"],
    ["Rzav", "Nebenfluss der Drina"],
    ["Saale", "Fluss in Deutschland"],
    ["Saane", "Fluss in der Schweiz"],
    ["Saar", "Rechter Nebenfluss der Mosel"],
    ["Sado", "Fluss in Portugal"],
    ["Sal", "Nebenfluss des Dons"],
    ["San", "Fluss in der Ukraine"],
    ["Save", "Nebenfluss der Donau in Südost-Europa"],
    ["Selz", "Nebenfluss des Rheins"],
    ["Seman", "Fluss in Albanien"],
    ["Senne", "Fluss zur Dijle in Belgien"],
    ["Sepik", "Fluss in Neuguinea"],
    ["Siak", "Fluss in Indonesien"],
    ["Sill", "Nebenfluss des Inns in Tirol"],
    ["Sjas", "Fluss im Nordwesten Russlands"],
    ["Sobat", "Fluss in Südsudan"],
    ["Spey", "Fluss in Schottland"],
    ["Steyr", "Fluss in Österreich"],
    ["Stör", "Nebenfluss der Elbe"],
    ["Stryj", "Nebenfluss des Dnisters"],
    ["Styr", "Rechter Nebenfluss des Prypjats"],
    ["Suir", "Fluss in Irland"],
    ["Sura", "Nebenfluss der Wolga"],
    ["Syr", "Nebenfluss der Mosel"],
    ["Taff", "Fluss in Wales"],
    ["Tajo", "Fluss in Spanien"],
    ["Tana", "Fluss in Kenia"],
    ["Tano", "Fluss in der Elfenbeinküste"],
    ["Tapi", "Fluss in Thailand"],
    ["Tara", "Fluss in Montenegro"],
    ["Tarn", "Nebenfluss der Garonne in Frankreich"],
    ["Tas", "Fluss in Russland"],
    ["Tech", "Zufluss des Mittelmeers in Frankreich"],
    ["Teme", "Fluss in Wales"],
    ["Terek", "Fluss im Kaukasus"],
    ["Thur", "Fluss in der Schweiz"],
    ["Tinto", "Fluss im Südwesten Spaniens"],
    ["Tjui", "Nebenfluss der Ufa in Russland"],
    ["Tobol", "Fluss in Kasachstan und Russland"],
    ["Toce", "Fluss im Piemont, Italien"],
    ["Tom", "Rechter Nebenfluss des Ob in Russland"],
    ["Trave", "Strom zur Ostsee in Schleswig-Holstein"],
    ["Trent", "Fluss in England"],
    ["Tumen", "Fluss in Nordostasien"],
    ["Tuul", "Fluss in der Mongolei"],
    ["Tym", "Rechter Nebenfluss des Ob in Russland"],
    ["Uda", "Zufluss der Selenga in Russland"],
    ["Udaj", "Fluss in der Ukraine"],
    ["Ugab", "Fluss in Namibia"],
    ["Ugra", "Linker Nebenfluss der Oka in Russland"],
    ["Ulba", "Fluss in Kasachstan"],
    ["Una", "Nebenfluss der Save"],
    ["Upa", "Rechter Nebenfluss der Oka in Russland"],
    ["Ure", "Fluss in England"],
    ["Usch", "Nebenfluss des Laborecs"],
    ["Usora", "Fluss in Bosnien und Herzegowina"],
    ["Ussa", "Nebenfluss der Petschora"],
    ["Usta", "Nebenfluss der Wetluga"],
    ["Uswa", "Nebenfluss der Tschussowaja"],
    ["Utwa", "Fluss in Kazakhstan"],
    ["Uvac", "Nebenfluss des Lims"],
    ["Vaal", "Fluss in Südafrika"],
    ["Vedea", "Nebenfluss der Donau"],
    ["Vesle", "Nebenfluss der Aisne"],
    ["Viaur", "Nebenfluss des Aveyron in Frankreich"],
    ["Vils", "Nebenfluss der Donau"],
    ["Vire", "Zufluss des Ärmelkanals in Frankreich"],
    ["Vjosa", "Fluss in Albanien und Griechenland"],
    ["Volta", "Fluss in Westafrika"],
    ["Vrbas", "Fluss in Bosnien und Herzegowina"],
    ["Vuka", "Fluss in Kroatien"],
    ["Waag", "Nebenfluss der Donau"],
    ["Waal", "Fluss in den Niederlanden"],
    ["Wear", "Fluss in England"],
    ["Wit", "Fluss in Bulgarien"],
    ["Witim", "Fluss in Sibirien, Russland"],
    ["Würm", "Nebenfluss der Amper"],
    ["Wye", "Fluss in Wales und England"],
    ["Yalu", "Fluss in Nordkorea"],
    ["Yare", "Fluss im Vereinigten Königreich"],
    ["Ybbs", "Fluss in Österreich"],
    ["Yser", "Fluss in Belgien und Frankreich"],
    ["Zaan", "Fluss in den Niederlanden"],
    ["Zala", "Fluss im Südwesten Ungarns"],
    ["Zeta", "Fluss in Montenegro"],
    ["Ziwil", "Nebenfluss der Wolga"],
    ["Ziz", "Fluss in Marokko und in Algerien"],
    ["Zna", "Linker Nebenfluss der Mokscha"]
  ]
}
