import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdInseln: Category = {
  id: "geografie",
  label: "Geografie",
  source: 'wikidata',
  entries: [
    ["Alofi", "Insel in Frankreich"],
    ["Als", "Dänische Insel in Nordschleswig"],
    ["Amrum", "Deutsche Nordseeinsel"],
    ["Andros", "Griechische Insel der Kykladen"],
    ["Aniwa", "Insel im Südosten Vanuatus"],
    ["Anuta", "Insel auf den Salomonen"],
    ["Arter", "Insel in der Türkei"],
    ["Aruad", "Archäologische Stätte in Syrien"],
    ["Atiu", "Insel in den Cookinseln"],
    ["Attu", "Insel der zu Alaska gehörenden Alëuten"],
    ["Aukena", "Insel in Französisch-Polynesien"],
    ["Aves", "Insel in Venezuela"],
    ["Banaba", "Insel im Pazifischen Ozean"],
    ["Barra", "Insel im Nordatlantik"],
    ["Bely", "Russische Insel in der Karasee"],
    ["Beqa", "Insel in Fidschi"],
    ["Beru", "Insel in Kiribati"],
    ["Betio", "Insel des Tarawa-Atolls, Kiribati"],
    ["Bigeh", "Insel in Ägypten"],
    ["Bintan", "Insel in Indonesien"],
    ["Bioko", "Insel in Äquatorialguinea"],
    ["Birnie", "Atoll der Phoenixinseln, Kiribati"],
    ["Bohol", "Insel auf den Philippinen"],
    ["Borneo", "Insel in Asien"],
    ["Brava", "Insel der Kapverden"],
    ["Bugio", "Insel in Portugal"],
    ["Buka", "Insel in Papua-Neuguinea"],
    ["Burano", "Insel in der Lagune von Venedig"],
    ["Buru", "Insel in Indonesien"],
    ["Capri", "Insel bei Neapel"],
    ["Cebu", "Insel auf den Philippinen"],
    ["Chios", "Griechische Insel"],
    ["Coche", "Insel in Venezuela"],
    ["Corvo", "Insel der Azoren"],
    ["Cres", "Kroatische Insel"],
    ["Darsa", "Insel im Jemen"],
    ["Das", "Insel vor Abu Dhabi, Ölverladehafen"],
    ["Delma", "Insel in den Emiraten"],
    ["Delos", "Insel im Ägäischen Meer"],
    ["Dokos", "Der Insel"],
    ["Dolin", "Insel in Kroatien"],
    ["Efate", "Insel des Inselstaats Vanuatu"],
    ["Eldey", "Insel in Island"],
    ["Euböa", "Griechische Insel"],
    ["Faray", "Insel der Orkneys in Schottland"],
    ["Farsi", "Insel im Iran"],
    ["Filfla", "Insel in Malta"],
    ["Foa", "Insel in Tonga"],
    ["Fogo", "Insel der Kapverdischen Inseln"],
    ["Föhr", "Deutsche Nordseeinsel"],
    ["Fotö", "Ort in der Gemeinde Öckerö, Schweden"],
    ["Gaua", "Insel in Vanuatu"],
    ["Gozo", "Insel des Archipels der Republik Malta"],
    ["Gröde", "Insel in Deutschland"],
    ["Guam", "Insel in den USA"],
    ["Harmil", "Insel in Eritrea"],
    ["Herm", "Kleinste bewohnte Insel im Ärmelkanal"],
    ["Hirta", "Abgelegene schottische Insel"],
    ["Hiu", "Insel in Vanuatu"],
    ["Hooge", "Insel in Deutschland"],
    ["Hopen", "Insel in Norwegen"],
    ["Hoste", "Insel in Chile"],
    ["Hvar", "Kroatische Insel"],
    ["Ibo", "Insel in Mosambik"],
    ["Iona", "Insel in Großbritannien"],
    ["Islay", "Südlichste Insel der Inneren Hebriden"],
    ["Jaco", "Osttimoresische Insel"],
    ["Jaina", "Archäologischer Fundplatz in Mexiko"],
    ["Java", "Insel in Indonesien"],
    ["Jejudo", "Südkoreanische Vulkaninsel"],
    ["Jemo", "Insel in den Marshallinseln"],
    ["Jindo", "Insel in Südkorea"],
    ["Jolo", "Insel auf den Philippinen"],
    ["Jukdo", "Südkoreanische Insel"],
    ["Keri", "Insel in Estland"],
    ["Ketoi", "Insel in Russland"],
    ["Kihnu", "Insel und Gemeinde in Estland"],
    ["Kisar", "Indonesische Insel"],
    ["Kisch", "Insel im Iran"],
    ["Komodo", "Insel in Indonesien"],
    ["Korfu", "Griechische Insel im Ionischen Meer"],
    ["Koror", "Insel in Palau"],
    ["Kos", "Griechische Insel"],
    ["Krk", "Kroatische Insel"],
    ["Kunoy", "Färöische Insel"],
    ["Kusu", "Insel in Singapur"],
    ["Lamu", "Insel in Kenia"],
    ["Larak", "Insel im Iran"],
    ["Lavan", "Insel im Iran"],
    ["Laysan", "Teil der Hawaianischen Inseln"],
    ["Lemuy", "Insel in Chile"],
    ["Leros", "Insel der Südlichen Sporaden"],
    ["Lib", "Insel in den Marshallinseln"],
    ["Lipsi", "Griechische Dodekanes-Insel"],
    ["Lokrum", "Insel in Kroatien"],
    ["Lombok", "Insel in Indonesien"],
    ["Lopud", "Kroatische Insel"],
    ["Lundy", "Insel in England"],
    ["Luzon", "Größte Insel der Philippinen"],
    ["Mafia", "Insel in Tansania"],
    ["Maiao", "Insel in Französisch-Polynesien"],
    ["Maio", "Eine der Kapverdischen Inseln"],
    ["Makira", "Insel auf den Salomonen"],
    ["Malo", "Insel des Inselstaats Vanuatu"],
    ["Manda", "Insel in Kenia"],
    ["Manra", "Atoll der Phoenixinseln, Kiribati"],
    ["Manus", "Insel vor der Küste Papua-Neuguineas"],
    ["Maore", "Insel in Frankreich"],
    ["Maui", "Zweitgrößte Hauptinsel Hawaiis"],
    ["Mauke", "Insel im Südpazifik"],
    ["Mbamu", "Insel in der Republik Kongo"],
    ["Moala", "Insel der Lau-Inseln"],
    ["Mocha", "Insel in Chile"],
    ["Mona", "Insel in den Vereinigten Staaten"],
    ["Mota", "Insel in Vanuatu"],
    ["Mousa", "Schottische Shetlandinsel"],
    ["Murano", "Insel in Italien"],
    ["Musha", "Insel in Dschibuti"],
    ["Nevis", "Insel in der Karibik"],
    ["Nias", "Indonesische Insel im Indischen Ozean"],
    ["Nihoa", "Insel in den USA"],
    ["Nora", "Insel in Eritrea"],
    ["Olchon", "Insel im Baikalsee"],
    ["Oleni", "Russische Insel in der Karasee"],
    ["Ons", "Insel in Spanien"],
    ["Orona", "Atoll der Phoenixinseln, Kiribati"],
    ["Orust", "Insel in Schweden"],
    ["Paama", "Insel in Vanuatu"],
    ["Pagan", "Insel in den USA"],
    ["Papey", "Insel in Island"],
    ["Paros", "Griechische Kykladeninsel"],
    ["Paxos", "Insel in Griechenland"],
    ["Pemba", "Tansanische Insel"],
    ["Perim", "Insel und Siedlung vor Aden im Jemen"],
    ["Pico", "Zweitgrößte Insel der Azoren"],
    ["Pinta", "Insel in Ecuador"],
    ["Poros", "Griechische Insel im Saronischen Golf"],
    ["Rab", "Kroatische Insel"],
    ["Rabi", "Insel in Fidschi"],
    ["Rebun", "Insel in Japan"],
    ["Replot", "Insel in Finnland"],
    ["Rhodos", "Insel Griechenlands"],
    ["Rota", "Insel in den Vereinigten Staaten"],
    ["Ruhnu", "Insel in Estland"],
    ["Run", "Insel der Banda-Inseln"],
    ["Runde", "Insel in Norwegen"],
    ["Runit", "Insel in den Marshallinseln"],
    ["Saba", "Insel in den Niederlanden"],
    ["Saipan", "Insel der USA im Pazifischen Ozean"],
    ["Samar", "Insel der Philippinen"],
    ["Samha", "Insel im Jemen"],
    ["Samos", "Griechische Insel"],
    ["Saria", "Insel in Griechenland"],
    ["Sark", "Insel in Guernsey"],
    ["Sazan", "Insel in Albanien"],
    ["Scarba", "Insel im Vereinigten Königreich"],
    ["Senja", "Insel in Norwegen"],
    ["Seram", "Insel im Archipel der Molukken"],
    ["Silba", "Insel in Kroatien"],
    ["Siri", "Insel im Iran"],
    ["Sitra", "Insel in Bahrain"],
    ["Soay", "Insel in Großbritannien"],
    ["Souda", "Insel nördlich von Kreta"],
    ["Sumba", "Indonesische Insel"],
    ["Susak", "Kroatische Insel"],
    ["Syrna", "Griechische Insel in der Ägäis"],
    ["Tahiti", "Insel im Südpazifik"],
    ["Taipa", "Insel in Volksrepublik China"],
    ["Taiwan", "Insel im Ostasien"],
    ["Tanna", "Insel des Inselstaates Vanuatu"],
    ["Tarut", "Insel in Saudi-Arabien"],
    ["Tegua", "Insel des Staates Vanuatu"],
    ["Temoe", "Atoll im Südpazifik"],
    ["Tidra", "Insel in Mauretanien"],
    ["Timor", "Insel in Südostasien"],
    ["Tino", "Italienische Insel im Ligurischen Meer"],
    ["Tiran", "Insel im Roten Meer"],
    ["Tobi", "Insel im Westpazifik"],
    ["Tresco", "Insel im Vereinigten Königreich"],
    ["Tusla", "Insel in der Straße von Kertsch"],
    ["Ubin", "Granitsteinbruch-Insel von Singapur"],
    ["Ukko", "Insel in der finnischen Gemeinde Inari"],
    ["Ummanz", "Deutsche Ostseeinsel"],
    ["Umnak", "Insel in den Vereinigten Staaten"],
    ["Unije", "Kroatische Insel"],
    ["Unst", "Insel im Vereinigten Königreich"],
    ["Upolu", "Insel in Samoa"],
    ["Urup", "Insel in Russland"],
    ["Usedom", "Deutsch-polnische Ostseeinsel"],
    ["Utila", "Siedlung in Honduras"],
    ["Utö", "Insel in der finnischen Stadt Pargas"],
    ["Uvea", "Insel im Südpazifik"],
    ["Vanna", "Insel in Norwegen"],
    ["Ven", "Schwedische Insel"],
    ["Vigur", "Insel in Island"],
    ["Vir", "Insel in Kroatien"],
    ["Vis", "Kroatische Insel"],
    ["Weno", "Stadt im Chuuk-Atoll, Mikronesien"],
    ["Wyre", "Insel der schottischen Orkneys"],
    ["Zuqar", "Insel im Jemen"]
  ]
}
