import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdKleidung: Category = {
  id: "alltag",
  label: "Alltag & Essen",
  source: 'wikidata',
  entries: [
    ["A-Linie", "Modesilhouette für Damenbekleidung"],
    ["Abscam", "Operation des FBI"],
    ["Albe", "Kleidungsstück"],
    ["Amaranten-Orden", "Ehemaliger schwedischer Ritterorden"],
    ["Atef-Krone", "Altägyptische Insigne"],
    ["Baronet", "Adelstitel im Vereinigten Königreich"],
    ["Blutorden", "Ehrenzeichen der NSDAP"],
    ["Chepresch", "Altägyptische Kopfbedeckung"],
    ["Chorhemd", "Liturgisches weißes Gewand"],
    ["Coppergate-Helm", "Kleidungsstück"],
    ["Dannebrogorden", "Dänischer Verdienstorden"],
    ["Dendra-Rüstung", "Antike griechische Schutzwaffe"],
    ["Deshret", "Rote Krone des Nordens"],
    ["Dirndl", "Kleidungsstück"],
    ["Drachenorden", "Katholischer Adelsorden"],
    ["Drehorgel", "Mechanisches Musikinstrument"],
    ["Edwardskrone", "Britische Krönungskrone"],
    ["Ehrenlegion", "Französischer Verdienstorden"],
    ["Freiheitsorden", "Portugiesischer Orden"],
    ["Fustanella", "Traditioneller Männerrock"],
    ["Gartel", "Kultischer Gürtel aus Wolle oder Seide"],
    ["Georgs-Kreuz", "Britische Zivilistenauszeichnung"],
    ["Georgsorden", "Hausorden der Wittelsbacher"],
    ["Gjermundbu-Helm", "Helm aus Norwegen"],
    ["Gummistiefel", "Kleidungsstück"],
    ["Halskragen", "Altägyptischer Schmuck"],
    ["Hennen-Ei", "Das erste Fabergé-Ei"],
    ["Imperator", "Römischer Titel"],
    ["Kachha", "Kleidungsstück der Sikh"],
    ["Kiani-Krone", "Ehemalige persische Krönungskrone"],
    ["Kimono", "Traditionelle japanische Kleidung"],
    ["Kitenge", "Kleiderstoff für Blusen und Röcke"],
    ["Kubanschild", "Kampfabzeichen der deutschen Wehrmacht"],
    ["Lazarus-Orden", "Historischer katholischer Ritterorden"],
    ["Leinenpanzer", "Kleidungsstück"],
    ["Leopoldsorden", "Belgischer Verdienstorden"],
    ["Liakat-Medaille", "Osmanische Ehrung"],
    ["Manios-Spange", "Archäologisches Fundstück aus Italien"],
    ["Mehndi", "Ornamentale Körperbemalung mit Henna"],
    ["Montefortino", "Typus antiker römischer Helme"],
    ["Nemes-Kopftuch", "Kopftuch der Pharaonen"],
    ["Oberst", "Militärischer Rank in der US-Armee"],
    ["Opanke", "Sandalenartiger, flexibler Schuh"],
    ["Orarion", "Kleidungsstück"],
    ["Örnek", "Ornament der Krimtataren"],
    ["Pahlavi-Krone", "Krone der Pahlevi-Dynastie im Iran"],
    ["Pakol", "Kopfbedeckung für Männer"],
    ["Parka", "Robuste Wetterjacke"],
    ["Phelonion", "Liturgisches Obergewand"],
    ["Porkpie", "Ein runder Hut mit schmaler Krempe"],
    ["Pschent", "Altägyptische Doppelkrone"],
    ["Ruhmesorden", "Belarussischer Orden"],
    ["Sator-Quadrat", "Wörterquadrat mit mehreren Bedeutungen"],
    ["Shayla", "Kopfbedeckung für muslimische Frauen"],
    ["Shisha", "Wasserpfeife orientalischem Ursprungs"],
    ["Spanienkreuz", "Militärauszeichnung in NS-Deutschland"],
    ["Strohschuh", "Kleidungsstück"],
    ["Templerorden", "Geistlicher Ritterorden, 1120–1312"],
    ["Theresienorden", "Damenorden des Königreiches Bayern"],
    ["Uschakoworden", "Orden der Sowietunion"],
    ["Verdienstorden", "Orden der Ukraine"],
    ["Victoria-Orden", "Britischer Hausorden"],
    ["Warbonnet", "Kleidungsstück"],
    ["Wasaorden", "Schwedischer Verdienstorden"],
    ["Wenzelskrone", "Königskrone des Königreichs Böhmen"],
    ["Wyschywanka", "Hemd mit traditionellem Stickmuster"],
    ["Xhubleta", "Albanischer Trachtenrock"],
    ["Zarenkrone", "Krone der Kaiser von Russland"]
  ]
}
