import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdSeen: Category = {
  id: "geografie",
  label: "Geografie",
  source: 'wikidata',
  entries: [
    ["Abajasee", "See in Südäthiopien"],
    ["Abijatta", "See in Äthiopien"],
    ["Achensee", "See in Tirol"],
    ["Aibisee", "See in der Volksrepublik China"],
    ["Akan", "See in Japan"],
    ["Ala-Kul", "Bergsee in Kirgisistan"],
    ["Almsee", "See in Österreich"],
    ["Alpsee", "See im Ostallgäu"],
    ["Amara-See", "See in Rumänien"],
    ["Ammersee", "See in Deutschland"],
    ["Apavatn", "See im Süden Islands"],
    ["Asveja", "See in Litauen"],
    ["Attersee", "See in Oberösterreich"],
    ["Awasasee", "See in Äthiopien"],
    ["Balaton", "Abflussloser Steppensee in Westungarn"],
    ["Bandak", "See in Norwegen"],
    ["Batur-See", "See auf Bali, Indonesien"],
    ["Bygdin", "See in Norwegen"],
    ["Chamosee", "See in Südäthiopien"],
    ["Cohoha", "See zwischen Ruanda und Burundi"],
    ["Dal-See", "See in Jammu und Kashmir, Indien"],
    ["Donuslaw", "Tiefster See der Schwarzmeerregion"],
    ["Drawsko", "See in Polen"],
    ["Drywjaty", "See in Belarus"],
    ["Dümmer", "See in Niedersachsen, Deutschland"],
    ["Eemmeer", "See in den Niederlanden"],
    ["Eibsee", "See in Deutschland"],
    ["Eriesee", "See in Kanada"],
    ["Esromsee", "Gewässer in Dänemark"],
    ["Eyasisee", "See in Tansania"],
    ["Fitri-See", "See im Tschad"],
    ["Galvesee", "See in Litauen"],
    ["Gardasee", "See in Norditalien"],
    ["Georgsee", "See in Uganda"],
    ["Gooimeer", "See in den Niederlanden"],
    ["Goplosee", "See in Polen"],
    ["Harku-See", "See im Norden Estlands"],
    ["Hayksee", "See in Äthiopien"],
    ["Hornavan", "See in Schweden"],
    ["Hulun-See", "See in der Volksrepublik China"],
    ["Huronsee", "See in den USA"],
    ["Hvalvatn", "See in Island"],
    ["Idrosee", "See in Italien"],
    ["Ilmensee", "See in der Nähe von Nowgorod"],
    ["Imandra", "See in Russland"],
    ["Indersee", "See in Kasachstan"],
    ["Iro-See", "See im Tschad"],
    ["Iseosee", "See in Oberitalien"],
    ["Jamno", "See in Polen"],
    ["Jipe-See", "See in Ostafrika"],
    ["Karakul", "See in der Volksrepublik China"],
    ["Karersee", "Bergsee in den Dolomiten"],
    ["Karumsee", "See in Äthiopien"],
    ["Keret", "See in Karelien, Russland"],
    ["Kisch-See", "See in Lettland"],
    ["Kiwusee", "Meromiktischer See in Zentralafrika"],
    ["Lamasee", "See in Sibirien (Russland)"],
    ["Lanao-See", "See auf den Philippinen"],
    ["Langano", "See in Äthiopien"],
    ["Limingen", "See in Norwegen"],
    ["Lugu-See", "See in Sichuan und Yunnan, China"],
    ["Mälaren", "See in Schweden"],
    ["Mamry", "See in Polen"],
    ["Miedwie", "See in der Pommerschen Seenplatte"],
    ["Mondsee", "See im Salzkammergut in Oberösterreich"],
    ["Müritz", "See in Deutschland"],
    ["Mwerusee", "See in dem Kongo"],
    ["Naratsch", "See in Belarus"],
    ["Nazik-See", "See in Ahlat, Bitlis, Türkei"],
    ["Niegocin", "See in Polen"],
    ["Njuk", "See in Karelien"],
    ["No-See", "See in Südsudan"],
    ["Nyos-See", "See in Kamerun"],
    ["Ohridsee", "Zweitgrößter See der Balkanhalbinsel"],
    ["Onegasee", "Großer See in Nordwestrussland"],
    ["Orivesi", "See in Finnland"],
    ["Ortasee", "See im Piemont, Italien"],
    ["Parawani", "See in Georgien"],
    ["Phewa-See", "See in Nepal"],
    ["Pjaosero", "See im Nordwesten von Russland"],
    ["Puruvesi", "See in Finnland"],
    ["Puula", "See in Finnland"],
    ["Qarun-See", "See in der ägyptischen Senke al-Faiyum"],
    ["Rarasee", "See in Nepal"],
    ["Riza-See", "See in Georgien"],
    ["Rogen", "See in Norwegen und Schweden"],
    ["Rotsee", "See im Kanton Luzern, Schweiz"],
    ["Roxen", "See in Schweden"],
    ["Rugwero", "See in Burundi und Ruanda"],
    ["Saimaa", "Seensystem in Finnland"],
    ["Saressee", "See im östlichen Tadschikistan"],
    ["Sartai", "See in Litauen"],
    ["Segosero", "Stausee in Russland"],
    ["Sentani", "See in Indonesien"],
    ["Sewansee", "Größter Süßwassersee Armeniens"],
    ["Siljan", "See in Schweden"],
    ["Synewyr", "See im Oblast Transkarpatien, Ukraine"],
    ["Taalsee", "See in den Philippinen"],
    ["Tanasee", "See in Äthiopien"],
    ["Tele-See", "See in dem Kongo"],
    ["Titisee", "See im südlichen Schwarzwald"],
    ["Tjörnin", "See in Island"],
    ["Togosee", "See in Togo"],
    ["Totasee", "Hochandensee in Kolumbien"],
    ["Traunsee", "See in Oberösterreich"],
    ["Tumbasee", "See in dem Kongo"],
    ["Umbosero", "See in der Oblast Murmansk (Russland)"],
    ["Uzungöl", "See in der Türkei"],
    ["Vänern", "Größter See in Schweden"],
    ["Vättern", "See in Schweden"],
    ["Vicosee", "See in Mittelitalien"],
    ["Volvi-See", "See in Griechenland"],
    ["Warna-See", "Liman bei Warna, Bulgarien"],
    ["Westsee", "See in der Volksrepublik China"],
    ["Wigry", "See in Polen"],
    ["Wygosero", "Stausee in Russland"],
    ["Yliki-See", "See in Griechenland"],
    ["Yoa-See", "See im Tschad"],
    ["Ziway", "See in Äthiopien"],
    ["Zugersee", "See in der Zentralschweiz"]
  ]
}
