import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdSport: Category = {
  id: "kulturSport",
  label: "Kultur & Sport",
  source: 'wikidata',
  entries: [
    ["Amateurringen", "Amateurform des Ringens"],
    ["Artifact", "Sportart"],
    ["Automobilsport", "Form des Motorsports"],
    ["Baguazhang", "Chinesischer Stil der Kampfkunst"],
    ["Bandy", "Ball- und Mannschaftssportart auf Eis"],
    ["Bare-knuckle", "Boxen mit der bloßen Faust"],
    ["Base-Jumping", "Fallschirmspringen von festen Objekten"],
    ["Beachhandball", "Sportdisziplin von Handball"],
    ["Bergrennen", "Disziplin innerhalb des Motorsports"],
    ["Bergsteigen", "Form des Bergsports"],
    ["Bierball", "Trinkspiel im Freien"],
    ["Blindschach", "Form des Schachspiels"],
    ["Boccia", "Variante des Boule-Spiels"],
    ["Boston-Marathon", "US-amerikanischer Marathonlauf"],
    ["Brawlhalla", "Kostenloses Kampf-Computerspiel"],
    ["Breaking", "Tanzform der Hip-Hop-Szene"],
    ["Bubble-Fußball", "Abwandlung des Fußballspiels"],
    ["Buckelpiste", "Unebene Skipiste"],
    ["Bunkai", "Trainingsform im Karate"],
    ["Cirit", "Türkisches Reiterspiel"],
    ["Crossfire", "Computerspiel aus dem Jahr 2007"],
    ["Damenproblem", "Schachmathematische Aufgabe"],
    ["Dodgeball", "Ballspiel ähnlich Völkerball"],
    ["Dofus", "Computerspiel aus dem Jahr 2004"],
    ["Dolichos", "Antikes Olympisches lauf Ereignis"],
    ["Downhill", "Bergabfahrt, vor allem im Radsport"],
    ["Dressurreiten", "Disziplin des Pferdesports"],
    ["Duathlon", "Triathlon ohne Schwimmen"],
    ["Einer", "Bootsklasse im Rudersport"],
    ["Eisklettern", "Disziplin im Klettersport"],
    ["Eiskunstlauf", "Form des Eislaufs"],
    ["Eisschnelllauf", "Eislaufen im Wettbewerb"],
    ["Eistanz", "Olympische Eiskunstlaufdisziplin"],
    ["Eskrima", "Form der philippinischen Kampfkünste"],
    ["Fear", "Computerspiel aus dem Jahr 2005"],
    ["Feldhandball", "Sportdisziplin im Handball"],
    ["Florett", "Fechtwaffe, Stoßwaffe oder Stichwaffe"],
    ["Freiklettern", "Form des Kletterns ohne Kletterhilfen"],
    ["Gerätturnen", "Individualsportart an Turngeräten"],
    ["Goalball", "Sportart für Sehbehinderte und Blinde"],
    ["Grappling", "Element vieler Kampfsportarten"],
    ["Grid", "Computerspiel aus dem Jahr 2019"],
    ["Hilfsmatt", "Ersonnene Schachaufgabe"],
    ["Hindernislauf", "Hindernisrennen in der Leichtathletik"],
    ["Hnefatafl", "Brettspiel skandinavischen Ursprungs"],
    ["Hockeysport", "Gruppe von Sportarten"],
    ["Indoorklettern", "Klettersport in der Halle"],
    ["Janggi", "Nationale Schachvariante Koreas"],
    ["Jonglieren", "Artistische Bewegungskunst"],
    ["Kaatsen", "Friesischer Ballsport"],
    ["Kabaddi", "Indische Mannschaftssportart"],
    ["Kampfkunst", "Techniken und Traditionen des Kampfes"],
    ["Kampfsport", "Art von Kraftsport"],
    ["Kanumarathon", "Kanusport Disziplin"],
    ["Kanurennsport", "Disziplin des Kanusports"],
    ["Kanuslalom", "Wettkampfdisziplin des Kanusports"],
    ["Kiiking", "Sportart aus Estland"],
    ["Kraftdreikampf", "Wettkampfsportart des Kraftsports"],
    ["Kunstradfahren", "Sportart"],
    ["Kurash", "Reihe von Volkswrestling Stilen"],
    ["London-Marathon", "Britischer Marathon"],
    ["Mah-Jongg", "Chinesisches Spiel"],
    ["Makruk", "Thailändische Schachvariante"],
    ["Novuss", "Sportart des Carrom"],
    ["Omnium", "Mehrkampf im Bahnradsport"],
    ["Painkiller", "Computerspiel aus dem Jahr 2004"],
    ["Paintball", "Sportart"],
    ["Paladins", "Computerspiel aus dem Jahr 2016"],
    ["Parabadminton", "Badminton für Behinderte"],
    ["Paris-Marathon", "Französischer Marathon"],
    ["Peking-Marathon", "Chinesischer Marathon"],
    ["Pelota", "Ballspiel baskischen Ursprungs"],
    ["Pesäpallo", "Finnisches Baseball"],
    ["Poolbillard", "Variante des Billards"],
    ["Punktefahren", "Disziplin im Bahnradsport"],
    ["Puroresu", "Japanisches Wrestling"],
    ["Rallye", "Wettbewerb im Motorsport"],
    ["Rasenbowlen", "Britische Variante des Boule-Spiels"],
    ["Rennrollstuhl", "Sportgerät für Rollstuhlfahrer"],
    ["Riesenslalom", "Sportart des Ski Alpin"],
    ["Rodeo", "Zweitbeliebtester Sports Chiles"],
    ["Rollstuhlrugby", "Mannschaftssportart für Athleten"],
    ["Rom-Marathon", "Italienischer Marathon"],
    ["Rudersport", "Olympische Wassersportart"],
    ["Sambo", "Russisch-sowjetische Kampfsportart"],
    ["Savate", "Französischer Kampfsport"],
    ["Schatrandsch", "Vorläufer des modernen Schachspiels"],
    ["Schwimmsport", "Sportart des Schwimmens"],
    ["Scratch", "Disziplin im Bahnradsport"],
    ["Shorttrack", "Disziplin des Eisschnelllaufs"],
    ["Shuaijiao", "Modernes chinesische Wort für Ringen"],
    ["Shuffleboard", "Spiel und Sportart"],
    ["Slamball", "US-amerikanische Ballsportart"],
    ["Slopestyle", "Akrobatische Wintersportdisziplin"],
    ["Smite", "Computerspiel aus dem Jahr 2014"],
    ["Snooker", "Variante des Billard"],
    ["Snowvolleyball", "Variante des Volleyballs im Schnee"],
    ["Softball", "Ballsportart, Variante des Baseball"],
    ["Speedklettern", "Olympische Disziplin"],
    ["Spieler", "Person, die ein Spiel spielt"],
    ["Splatoon", "Videospiel aus dem Jahr 2015"],
    ["Sportaerobic", "Wettkampfform der Aerobic"],
    ["Sportklettern", "Form des Freikletterns"],
    ["Sporttauchen", "Tauchen als Breitensport"],
    ["Springreiten", "Disziplin des Pferdesports"],
    ["Squash", "Sportart mit Schlägern für Rückschlag"],
    ["Ssireum", "Alte koreanische Form des Ringens"],
    ["Stadionlauf", "Antike Leichtathletikdisziplin"],
    ["Steeplechase", "Form des Galopprennens"],
    ["Stockcar", "Sportart"],
    ["Straßenlauf", "Sportart"],
    ["Streetball", "Variante der Sportart Basketball"],
    ["Stundenlauf", "Sportart"],
    ["Sudoku", "Japanisches Zahlenraster-Logikrätsel"],
    ["Super-G", "Sportart im Skisport"],
    ["Taekwondo", "Koreanischer Kampfsport"],
    ["Tandemschach", "Sportart"],
    ["Tanzsport", "Tanzen als Sportart"],
    ["Teamsprint", "Disziplin im Bahnradsport"],
    ["Teeworlds", "Computerspiel aus dem Jahr 2007"],
    ["Telemarken", "Abfahrtstechnik beim Skifahren"],
    ["Tetris", "Puzzle-Computerspiel aus dem Jahr 1984"],
    ["Tokio-Marathon", "Japanischer Marathon"],
    ["Trabrennsport", "Variante des Pferderennsports"],
    ["Traillauf", "Sportart"],
    ["Valorant", "Kostenfreier Ego-Shooter"],
    ["Vorstieg", "Sicherungsmethode im Sportklettern"],
    ["Wakeboard", "Wassersportart ähnlich dem Wasserski"],
    ["Warsow", "Freier Egoshooter"],
    ["Wasserski", "Motorisierter Skisport auf dem Wasser"]
  ]
}
