import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdSprachen: Category = {
  id: "menschSprache",
  label: "Mensch & Sprache",
  source: 'wikidata',
  entries: [
    ["Achinesisch", "Sprache in Aceh auf Sumatra"],
    ["Ahtna", "Sprache"],
    ["Alemannisch", "Sprache"],
    ["Altaisch", "Sibirischer Zweig der Turksprachen"],
    ["Altnubisch", "Nilosaharanische Sprache"],
    ["Altsächsisch", "Germanische Sprache"],
    ["Anal", "Sinotibetische Sprache"],
    ["Andisch", "Sprache der Andier"],
    ["Anus", "Austronesische Sprache"],
    ["Arabisch", "Semitische Sprache"],
    ["Arakanesisch", "Sprache der Arakanesen"],
    ["Badaga", "Süddravidische Sprache"],
    ["Baktrisch", "Historische mitteliranische Sprache"],
    ["Banyumasan", "Sprache auf Java"],
    ["Bassa", "Sprache"],
    ["Belarussisch", "Ostslawische Sprache"],
    ["Beschtinisch", "Nordkaukasische Sprache"],
    ["Bulgarisch", "Südslawische Sprache"],
    ["Champenois", "Romanische Sprache"],
    ["Chinalugisch", "Nordostkaukasische Sprache"],
    ["Choresmisch", "Indogermanische Sprache"],
    ["Chuukesisch", "Sprache der Chuuk-Inseln"],
    ["Comanche", "Uto-aztekische Sprache"],
    ["Dagbani", "Sprache der Dagbmba in Ghana"],
    ["Dagurisch", "Mongolische Sprache"],
    ["Dahalik", "Äthio-semitische Sprache"],
    ["Dänisch", "Nordgermanische Sprache"],
    ["Dinka", "Westnilotische Sprache"],
    ["Dioula", "Westafrikanische Mande-Sprache"],
    ["Dogon", "Sprache in Westafrika"],
    ["Dzongkha", "Sprache"],
    ["Eblaitisch", "Ausgestorbene semitische Sprache"],
    ["Elsässisch", "Alemannische Dialekte im Elsass"],
    ["Englisch", "Westgermanische Sprache"],
    ["Ewenkisch", "Mandschu-tungusische Sprache"],
    ["Eyak", "Ausgestorbene Na-Dené-Sprache"],
    ["Farefare", "Sprache in Westafrika"],
    ["Färöisch", "Nordgermanische Sprache"],
    ["Frainc-Comtou", "Romanische Sprache"],
    ["Französisch", "Romanische Sprache"],
    ["Galicisch", "Romanische Sprache"],
    ["Gegisch", "Indogermanische Sprache"],
    ["Gilaki", "Iranische Sprache"],
    ["Harsusi", "Neusüdarabische Sprache"],
    ["Hebräisch", "Nordwestsemitische Sprache"],
    ["Indonesisch", "Amtssprache in Indonesien"],
    ["Inuinnaqtun", "Eskimo-aleutische Sprache"],
    ["Irula", "Dravidische Sprache"],
    ["Jarai", "Malayo-polynesische Sprache"],
    ["Javanisch", "Austronesische Sprache"],
    ["Jugisch", "Ausgestorbene jeniseische Sprache"],
    ["Kajkavisch", "Indogermanische Sprache"],
    ["Karakalpakisch", "Turksprache in Usbekistan"],
    ["Karisch", "Sprache des antiken Volks der Karer"],
    ["Katharevousa", "Ehemalige Amtssprache Griechenlands"],
    ["Khmer", "Amtssprache Kambodschas"],
    ["Kiribatisch", "Austronesische Sprache"],
    ["Koro", "In Indien gesprochene Sprache"],
    ["Kumbrisch", "Ausgestorbene keltische Sprache"],
    ["Kurukh", "Dravidische Sprache"],
    ["Ladinisch", "Romanische Sprache"],
    ["Langobardisch", "Ausgestorbene germanische Sprache"],
    ["Laotisch", "Staatssprache von Laos"],
    ["Latein", "Indogermanische Sprache"],
    ["Leonesisch", "Romanische Sprache"],
    ["Maa", "Sprache der Massai"],
    ["Makedonisch", "Indogermanische Sprache der Antike"],
    ["Mam", "Sprache in Mittelamerika"],
    ["Mazedonisch", "Südslawische Sprache"],
    ["Mittellatein", "Indogermanische Sprache"],
    ["Moghol", "Mongolische Sprache in Afghanistan"],
    ["Morisyen", "Kreolsprache von Mauritius"],
    ["Nanaisch", "Sprache der Nanai in Sibirien"],
    ["Nauruisch", "Austronesische Sprache aus Nauru"],
    ["Nheengatu", "Südamerikanische Sprache"],
    ["Nord-Ndebele", "Bantusprache; Hauptsprache in Simbabwe"],
    ["Nynorsk", "Sprache"],
    ["Olonetzisch", "Finnougrische Sprache"],
    ["Oriya", "Indoarische Sprache"],
    ["Ost-Yugurisch", "Mongolische Sprache"],
    ["Panjabi", "Indoarische Sprache"],
    ["Parthisch", "Historische mitteliranische Sprache"],
    ["Pfälzisch", "Deutsche Dialekte"],
    ["Piemontesisch", "Romanische Sprache"],
    ["Pomoranisch", "Slawische Sprache"],
    ["Russisch", "Ostslawische Sprache"],
    ["Sächsisch", "Ostmitteldeutsche Mundart"],
    ["Sango", "Afrikanische Sprache"],
    ["Santa", "Mongolische Sprache"],
    ["Schlesisch", "Westslawische Sprache"],
    ["Schwäbisch", "Oberdeutsche Mundart"],
    ["Seeländisch", "Indogermanische Sprache"],
    ["Seri", "Mexikanische Sprache"],
    ["Setswana", "Sprache im südlichen Afrika"],
    ["Sogdisch", "Mitteliranische Sprache"],
    ["Sonsorolesisch", "Mikronesische Sprache"],
    ["Sorbisch", "Westslawische Sprache"],
    ["Spanisch", "Sprache"],
    ["Südestnisch", "Dialekte des Estnischen"],
    ["Sundanesisch", "Malayo-polynesischen Sprache"],
    ["Susu", "Afrikanische Sprache"],
    ["Taa-Sprache", "Khoisansprache in Botswana und Namibia"],
    ["Tamascheq", "Südlicher Diakekt der Tuaregsprachen"],
    ["Tschulymisch", "Sprache"],
    ["Tzotzil-Sprache", "Indigene Sprache in Mexiko"],
    ["Ultschisch", "Sprache der Ultschen"],
    ["Urum", "Turksprache im Südosten der Ukraine"],
    ["Waigali", "Indogermanische Sprache"],
    ["Wasi-Weri", "Indogermanische Sprache"],
    ["Westarmenisch", "Sprache"],
    ["Wilmesaurisch", "Westgermanische Sprache"],
    ["Wotisch", "Finno-ugrische Sprache"],
    ["Zapotekisch", "Indigene Sprache in Mexiko"],
    ["Zarfatisch", "Ausgestorbene romanische Sprache"],
    ["Zentral-Bikol", "Philippinische Sprache"],
    ["Zimbrisch", "Germanische Sprache"]
  ]
}
