import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdStaedte: Category = {
  id: "geografie",
  label: "Geografie",
  source: 'wikidata',
  entries: [
    ["Aalst", "Stadt in Belgien"],
    ["Abakan", "Stadt in Russland"],
    ["Abidjan", "Stadt in der Elfenbeinküste"],
    ["Aichach", "Stadt in Bayern, Deutschland"],
    ["Akkad", "Stadt in dem Irak"],
    ["Aksum", "Stadt in Äthiopien"],
    ["Al-Ain", "Stadt in den Emiraten"],
    ["Alameda", "Stadt in Kalifornien"],
    ["Albenga", "Italienische Stadtgemeinde"],
    ["Almere", "Stadt und Gemeinde in den Niederlanden"],
    ["Anaheim", "Stadt im US-Bundesstaat Kalifornien"],
    ["Andria", "Stadt in Italien"],
    ["Angkor", "Stadt in Kambodscha"],
    ["Antalya", "Stadt in der Türkei"],
    ["Arica", "Stadt in Chile"],
    ["Arlon", "Stadt in Belgien"],
    ["Arnheim", "Stadt in den Niederlanden"],
    ["Arusha", "Stadt in Tansania"],
    ["Assen", "Niederländische Gemeinde"],
    ["Astana", "Hauptstadt von Kasachstan"],
    ["Asti", "Stadt in Italien"],
    ["Avignon", "Stadt in Frankreich"],
    ["Baalbek", "Stadt in dem Libanon"],
    ["Babylon", "Stadt in Seleukidenreich"],
    ["Badajoz", "Stadt in Spanien"],
    ["Bagan", "Historische Königsstadt in Myanmar"],
    ["Balzers", "Gemeinde in Liechtenstein"],
    ["Bamako", "Hauptstadt von Mali"],
    ["Bangor", "Stadt in Wales, Vereinigtes Königreich"],
    ["Bari", "Süditalienische Stadt"],
    ["Berehowe", "Stadt in der Ukraine"],
    ["Bergamo", "Stadt in Italien"],
    ["Bhopal", "Stadt in Indien"],
    ["Bilecik", "Stadt in der Türkei"],
    ["Bingöl", "Stadt in der Türkei"],
    ["Bitlis", "Landkreis und Stadt in der Türkei"],
    ["Bonn", "Stadt in Deutschland"],
    ["Brest", "Stadt in Belarus"],
    ["Brügge", "Stadt in Westflandern, Belgien"],
    ["Brünn", "Stadt in Tschechien"],
    ["Buchara", "Stadt in Usbekistan"],
    ["Budweis", "Stadt in Südböhmen"],
    ["Burbank", "Stadt in den USA"],
    ["Busan", "Großstadt in Südkorea"],
    ["Butrint", "Stadt in Albanien"],
    ["Calais", "Französische Gemeinde"],
    ["Cali", "Stadt in Kolumbien"],
    ["Carrara", "Italienische Gemeinde"],
    ["Celje", "Stadt in Slowenien"],
    ["Cesena", "Stadt in der Emilia-Romagna"],
    ["Chartum", "Hauptstadt des Sudan"],
    ["Chengdu", "Stadt in Volksrepublik China"],
    ["Chiba", "Stadt in Japan"],
    ["Chico", "Stadt in Kalifornien"],
    ["Chios", "Griechische Insel"],
    ["Colombo", "Faktische Hauptstadt von Sri Lanka"],
    ["Compton", "Stadt in den USA"],
    ["Comrat", "Stadt in der Republik Moldau"],
    ["Cork", "Stadt im südlichen Irland"],
    ["Cuneo", "Stadt im Piemont"],
    ["Dachau", "Stadt in Deutschland"],
    ["Daegu", "Südkoreanische Stadt"],
    ["Daejeon", "Großstadt in Südkorea"],
    ["Dalian", "Bezirksfreie Stadt in Liaoning, China"],
    ["Dandong", "Bezirksfreie Stadt in Liaoning, China"],
    ["Danzig", "Stadt in Polen"],
    ["Daraa", "Stadt in Syrien"],
    ["Darchan", "Stadt in Mongolei"],
    ["Darwin", "Stadt in Australien"],
    ["Delphi", "Stadt in Griechenland"],
    ["Dhaka", "Hauptstadt Bangladeschs"],
    ["Dodoma", "Hauptstadt von Tansania"],
    ["Dülmen", "Stadt in Nordrhein-Westfalen"],
    ["Durban", "Südafrikanische Metropole"],
    ["Eger", "Stadt in Ungarn"],
    ["Eilat", "Südlichste Stadt Israels"],
    ["Ely", "Stadt in Großbritannien"],
    ["Ephesos", "Antike Siedlung in der Türkei"],
    ["Erdenet", "Stadt in der Mongolei"],
    ["Eupen", "Stadt in Belgien"],
    ["Eureka", "Stadt in Kalifornien"],
    ["Ferrara", "Stadt in Oberitalien, Emilia-Romagna"],
    ["Fresno", "Stadt im US-Bundesstaat Kalifornien"],
    ["Fukuoka", "Großstadt in Japan"],
    ["Gaya", "Großstadt in Bihar, Indien"],
    ["Gdynia", "Stadt in Polen"],
    ["Geelong", "Stadt in Australien"],
    ["Gent", "Stadt in Flandern, Belgien"],
    ["Gizeh", "Stadt in Ägypten"],
    ["Glasgow", "Großstadt in Schottland"],
    ["Goslar", "Stadt in Niedersachsen"],
    ["Graz", "Stadt in Österreich"],
    ["Gwangju", "Stadt in Südkorea"],
    ["Hampton", "Stadt im US-Bundesstaat Virginia"],
    ["Harare", "Hauptstadt von Simbabwe"],
    ["Harbin", "Stadt in Volksrepublik China"],
    ["Hasselt", "Belgische Mittelstadt am Albert-Kanal"],
    ["Hatra", "Archäologische Stätte im Irak"],
    ["Hayward", "Stadt im US-Bundesstaat Kalifornien"],
    ["Helmond", "Stadt in den Niederlanden"],
    ["Herzlia", "Stadt in Israel nördlich Tel Aviv"],
    ["Imperia", "Italienische Gemeinde"],
    ["Incheon", "Stadt in Südkorea"],
    ["Iqaluit", "Stadt in Kanada"],
    ["Irkutsk", "Stadt in Russland"],
    ["Irvine", "Stadt in den USA"],
    ["Isfahan", "Stadt in dem Iran"],
    ["Ithaka", "Griechische Insel im Ionischen Meer"],
    ["Jericho", "Stadt in Palästina"],
    ["Jihlava", "Stadt in Tschechien"],
    ["Jinan", "Stadt in China"],
    ["Juba", "Hauptstadt des Südsudan"],
    ["Kaduna", "Ort in Nigeria"],
    ["Kenosha", "Stadt im US-Bundesstaat Wisconsin"],
    ["Khulna", "Stadt in Bangladesch"],
    ["Knossos", "Antike Stadt der Minoer"],
    ["Kolkata", "Stadt in Indien"],
    ["Koper", "Einzige Hafenstadt in Slowenien"],
    ["Kortrijk", "Gemeinde in Belgien"],
    ["Kowel", "Stadt in der Ukraine"],
    ["Krems", "Stadt in Österreich"],
    ["Kurume", "Ort in der Präfektur Fukuoka, Japan"],
    ["Kyrene", "Archäologischer Fundplatz in Libyen"],
    ["Kyrenia", "Stadt in der Republik Zypern"],
    ["Lahore", "Stadt in Pakistan"],
    ["Lanzhou", "Stadt in China"],
    ["Laredo", "Stadt in Texas, USA"],
    ["Larisa", "Stadt und Gemeinde in Griechenland"],
    ["Lefkada", "Insel im Ionischen Meer, Griechenland"],
    ["Leh", "Kleinstadt in Indien"],
    ["Lhasa", "Hauptstadt des Autonomen Gebiets Tibet"],
    ["Linz", "Stadt in Österreich"],
    ["Löwen", "Stadt in Belgien"],
    ["Luanda", "Hauptstadt von Angola"],
    ["Lucca", "Stadt in Italien"],
    ["Lugano", "Stadt im Kanton Tessin, Schweiz"],
    ["Lund", "Stadt in Schweden"],
    ["Lüttich", "Stadt in Wallonien, Belgien"],
    ["Luzk", "Stadt in der nordwestlichen Ukraine"],
    ["Majuro", "Hauptstadt der Marshallinseln"],
    ["Malmö", "Stadt in Schweden"],
    ["Maseru", "Hauptstadt von Lesotho"],
    ["Mbabane", "Hauptstadt von Eswatini"],
    ["Mechelen", "Gemeinde in Belgien"],
    ["Meißen", "Stadt in Deutschland"],
    ["Melilla", "Stadt in Spanien"],
    ["Memphis", "Stadt in Ägypten"],
    ["Merced", "Stadt in Kalifornien, USA"],
    ["Meroe", "Stadt in dem Sudan"],
    ["Merw", "Historische Stätte in Turkmenistan"],
    ["Milazzo", "Italienische Stadtgemeinde"],
    ["Milet", "Stadt in der Türkei"],
    ["Milos", "Stadt in Griechenland"],
    ["Miskolc", "Stadt in Ungarn"],
    ["Mito", "Ort in der Präfektur Ibaraki, Japan"],
    ["Modena", "Norditalienische Universitätsstadt"],
    ["Modesto", "Stadt in den USA"],
    ["Mombasa", "Stadt in Kenia"],
    ["Mons", "Stadt in der Wallonie, Belgien"],
    ["Monza", "Italienische Stadt"],
    ["Moroni", "Hauptstadt der Komoren"],
    ["Muggia", "Gemeinde in Italien"],
    ["Mumbai", "Stadt in Indien"],
    ["Murom", "Stadt in Russland"],
    ["Mykene", "Antike Stadt in Griechenland"],
    ["Nagano", "Großstadt in Japan"],
    ["Nagoya", "Stadt in Japan"],
    ["Naha", "Stadt auf Okinawa, Japan"],
    ["Namur", "Hauptstadt der Wallonie"],
    ["Nanjing", "Chinesische Millionenstadt"],
    ["Narwa", "Stadt in Estland"],
    ["Nassau", "Hauptstadt der Bahamas"],
    ["Neu-Ulm", "Große Kreisstadt in Bayern"],
    ["Newark", "Gemeinde im US-Bundesstaat New Jersey"],
    ["Nimrud", "Stadt in dem Irak"],
    ["Ningbo", "Bezirksfreie Stadt in Zhejiang, China"],
    ["Ninive", "Stadt in dem Irak"],
    ["Nippur", "Antike Stadt in Mesopotamien"],
    ["Novara", "Italienische Gemeinde"],
    ["Nuuk", "Hauptstadt von Grönland"],
    ["Oakland", "Stadt in den USA"],
    ["Olsztyn", "Stadt in Ermland-Masuren, Polen"],
    ["Opava", "Stadt in Tschechien"],
    ["Oradea", "Stadt in Rumänien"],
    ["Osaka", "Drittgrößte Stadt Japans"],
    ["Osch", "Stadt in Kirgisistan"],
    ["Osijek", "Kroatische Stadt am Ufer der Drau"],
    ["Ostende", "Stadt in Belgien"],
    ["Ostrava", "Großstadt in Tschechien"],
    ["Palermo", "Hauptstadt Siziliens"],
    ["Palma", "Hauptstadt von Mallorca, Spanien"],
    ["Palmyra", "Antike Oasenstadt in Syrien"],
    ["Paphos", "Stadt auf Zypern"],
    ["Patna", "Millionenstadt in Bihar, Indien"],
    ["Perth", "Stadt in Australien"],
    ["Petra", "Antike Felsenstadt in Jordanien"],
    ["Phuket", "Stadt in Thailand"],
    ["Pilsen", "Tschechische Großstadt"],
    ["Piran", "Stadt in Slowenien"],
    ["Pirna", "Stadt in Deutschland"],
    ["Pisa", "Stadt in der Toskana in Italien"],
    ["Plauen", "Stadt in Deutschland"],
    ["Pomona", "Stadt in den USA"],
    ["Pompeji", "Antike Stadt nahe Neapel in Italien"],
    ["Posadas", "Stadt in Argentinien"],
    ["Posen", "Stadt in Polen"],
    ["Prato", "Stadt in Italien"],
    ["Pskow", "Stadt in Russland"],
    ["Pula", "Stadt in Kroatien"],
    ["Puno", "Ort in Peru am Titicaca-See"],
    ["Qingdao", "Bezirksfreie Stadt in Shandong, China"],
    ["Racine", "Stadt im US-Bundesstaat Wisconsin"],
    ["Rajkot", "Millionenstadt in Gujarat, Indien"],
    ["Ranchi", "Hauptstadt von Jharkhand"],
    ["Rangun", "Stadt in Myanmar"],
    ["Ravenna", "Italienische Gemeinde"],
    ["Regina", "Stadt in Kanada"],
    ["Rhodos", "Insel Griechenlands"],
    ["Rijeka", "Hafenstadt in Kroatien"],
    ["Rimini", "Stadt an der italienischen Adriaküste"],
    ["Roanoke", "Stadt in Virginia, USA"],
    ["Rotorua", "Stadt in Neuseeland"],
    ["Rovinj", "Stadt in Kroatien"],
    ["Saitama", "Stadt in Japan"],
    ["Sakai", "Stadt in der Präfektur Osaka, Japan"],
    ["Salamis", "Griechische Insel im Saronischen Golf"],
    ["Salem", "Indische Stadt"],
    ["Samos", "Griechische Insel"],
    ["Sanaa", "Hauptstadt Jemens"],
    ["Sapporo", "Stadt in Japan"],
    ["Sassari", "Italienische Gemeinde auf Sardinien"],
    ["Savona", "Italienische Gemeinde"],
    ["Schaan", "Gemeinde in Liechtenstein"],
    ["Segovia", "Stadt in Spanien"],
    ["Sejong", "Stadt in Südkorea"],
    ["Sendai", "Stadt in Japan"],
    ["Sidon", "Siedlung in Libanon"],
    ["Siena", "Italienische Stadt in der Toskana"],
    ["Singapur", "Stadtstaat in Südostasien"],
    ["Sinop", "Stadt in der Türkei"],
    ["Sisak", "Stadt in Kroatien"],
    ["Sopron", "Stadt im Nordwesten von Ungarn"],
    ["Sparta", "Stadt in Griechenland"],
    ["Split", "Stadt in Kroatien"],
    ["Stettin", "Stadt in Polen"],
    ["Steyr", "Stadt in Österreich"],
    ["Stryj", "Ukrainische Stadt"],
    ["Sucre", "Hauptstadt von Bolivien"],
    ["Surat", "Millionenstadt in Gujarat, Indien"],
    ["Susa", "Antike Stadt im Südwestiran"],
    ["Szeged", "Großstadt in Ungarn"],
    ["Szolnok", "Stadt in Ungarn"],
    ["Tainan", "Regierungsunmittelbare Stadt in Taiwan"],
    ["Taipeh", "Hauptstadt der Republik China (Taiwan)"],
    ["Taras", "Stadt in Kasachstan"],
    ["Telawi", "Stadt in Georgien"],
    ["Teplice", "Stadt in Tschechien"],
    ["Termiz", "Stadt in Usbekistan"],
    ["Theben", "Antike Stadt in Ägypten"],
    ["Thimphu", "Stadt in Bhutan"],
    ["Thiva", "Stadt in Griechenland"],
    ["Tianjin", "Hafenstadt in der Volksrepublik China"],
    ["Tiflis", "Hauptstadt und größte Stadt Georgiens"],
    ["Toluca", "Stadt in Mexiko"],
    ["Tournai", "Stadt in Wallonien, Belgien"],
    ["Toyota", "Ort in der Präfektur Aichi, Japan"],
    ["Trenton", "Stadt im US-Bundesstaat New Jersey"],
    ["Treviso", "Italienische Gemeinde"],
    ["Triest", "Norditalienische Hafen- und Großstadt"],
    ["Trogir", "Stadt in Dalmatien, Kroatien"],
    ["Troja", "Stadt des Altertums"],
    ["Tudela", "Gemeinde in Spanien"],
    ["Tulcea", "Stadt in Rumänien"],
    ["Tychy", "Stadt in Polen"],
    ["Tyros", "Stadt in Libanon"],
    ["Ugarit", "Stadtstaat in der Antike"],
    ["Ujjain", "Stadt in Indien"],
    ["Ulsan", "Südkoreanische Stadt"],
    ["Unna", "Stadt in Nordrhein-Westfalen"],
    ["Uruk", "Stadt in dem Irak"],
    ["Vallejo", "Stadt im US-Bundesstaat Kalifornien"],
    ["Varese", "Italienische Gemeinde"],
    ["Verona", "Italienische Großstadt"],
    ["Vicenza", "Gemeinde in Norditalien"],
    ["Villach", "Stadt in Kärnten, Österreich"],
    ["Vukovar", "Stadt in Kroatien"],
    ["Wavre", "Stadt in Wallonie, Belgien"],
    ["Wismar", "Stadt in Mecklenburg-Vorpommern"],
    ["Wuhan", "Stadt in Volksrepublik China"],
    ["Xiamen", "Bezirksfreie Stadt in Fujian, China"],
    ["Yaren", "Stadt in Naoero"],
    ["Yozgat", "Stadt in der Türkei"],
    ["Ypern", "Gemeinde in Belgien"],
    ["Yuma", "Stadt im US-Bundesstaat Arizona"],
    ["Zadar", "Hafenstadt in Kroatien"],
    ["Zagazig", "Stadt in Ägypten"],
    ["Zapopan", "Stadt in Mexiko"],
    ["Zvolen", "Kleinstadt in der Slowakei"],
    ["Zwickau", "Stadt in Sachsen, Deutschland"],
    ["Zwolle", "Gemeinde in der Provinz Overijssel"]
  ]
}
