import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdVornamen: Category = {
  id: "menschSprache",
  label: "Mensch & Sprache",
  source: 'wikidata',
  entries: [
    ["Aake", "Vorname"],
    ["Aaron", "Männlicher Vorname"],
    ["Aiko", "Vorname"],
    ["Aisha", "Weiblicher Vorname (عائشة)"],
    ["Aki", "Geschlechtsneutraler Vorname"],
    ["Akio", "Männlicher Vorname"],
    ["Akira", "Geschlechtsneutraler Vorname"],
    ["Alba", "Geschlechtsneutraler Vorname"],
    ["Alex", "Geschlechtsneutraler Vorname"],
    ["Ali", "Geschlechtsneutraler Vorname"],
    ["Alla", "Weiblicher Vorname (Алла)"],
    ["Allie", "Vorname"],
    ["Alva", "Vorname"],
    ["Amal", "Vorname"],
    ["Amir", "Männlicher Vorname (أمير)"],
    ["Amr", "Männlicher Vorname"],
    ["Andi", "Geschlechtsneutraler Vorname"],
    ["Andy", "Geschlechtsneutraler Vorname"],
    ["Anna", "Weiblicher Vorname (Анна)"],
    ["Aria", "Geschlechtsneutraler Vorname"],
    ["Ariel", "Geschlechtsneutraler Vorname"],
    ["Arif", "Männlicher Vorname (عارف)"],
    ["Artem", "Männlicher Vorname (Артем)"],
    ["Arvid", "Männlicher Vorname"],
    ["Arvo", "Männlicher Vorname"],
    ["Arya", "Vorname"],
    ["Arzu", "Weiblicher Vorname"],
    ["Asa", "Geschlechtsneutraler Vorname"],
    ["Asma", "Weiblicher Vorname"],
    ["Assar", "Männlicher Vorname"],
    ["Atle", "Männlicher Vorname"],
    ["Audun", "Norwegischer Vorname"],
    ["Auke", "Männlicher Vorname"],
    ["Aulis", "Männlicher Vorname"],
    ["Aurel", "Männlicher Vorname"],
    ["Avery", "Geschlechtsneutraler Vorname"],
    ["Aydan", "Vorname"],
    ["Aykut", "Männlicher Vorname"],
    ["Ayla", "Weiblicher Vorname"],
    ["Aylin", "Weiblicher Vorname"],
    ["Aysel", "Weiblicher Vorname"],
    ["Aziz", "Vorname"],
    ["Aziza", "Weiblicher Vorname"],
    ["Azra", "Vorname"],
    ["Barry", "Männlicher Vorname"],
    ["Beda", "Männlicher Vorname"],
    ["Bella", "Weiblicher Vorname"],
    ["Ben", "Männlicher Vorname"],
    ["Bence", "Männlicher Vorname"],
    ["Bengt", "Männlicher Vorname"],
    ["Beno", "Männlicher Vorname"],
    ["Bent", "Männlicher Vorname"],
    ["Bente", "Weiblicher Vorname"],
    ["Berit", "Weiblicher Vorname"],
    ["Bernd", "Männlicher Vorname"],
    ["Beryl", "Geschlechtsneutraler Vorname"],
    ["Blake", "Männlicher Vorname"],
    ["Blas", "Männlicher Vorname"],
    ["Boris", "Männlicher Vorname (Борис)"],
    ["Calum", "Vorname"],
    ["Carol", "Geschlechtsneutraler Vorname"],
    ["Chris", "Geschlechtsneutraler Vorname"],
    ["Cora", "Weiblicher Vorname"],
    ["Csaba", "Männlicher Vorname"],
    ["Daiki", "Männlicher japanischer Vorname"],
    ["Dana", "Geschlechtsneutraler Vorname"],
    ["Dara", "Geschlechtsneutraler Vorname"],
    ["Darya", "Weiblicher Vorname (Дарья/Дария)"],
    ["Debra", "Weiblicher Vorname"],
    ["Deniz", "Vor- und Familienname"],
    ["Derya", "Geschlechtsneutraler Vorname"],
    ["Dolly", "Weiblicher Vorname"],
    ["Dunja", "Weiblicher Vorname"],
    ["Dylan", "Geschlechtsneutraler Vorname"],
    ["Eden", "Geschlechtsneutraler Vorname"],
    ["Edi", "Geschlechtsneutraler Vorname"],
    ["Edita", "Weiblicher Vorname"],
    ["Edna", "Weiblicher Vorname"],
    ["Eeva", "Estnisch-finnischer weiblicher Vorname"],
    ["Egil", "Männlicher Vorname"],
    ["Eija", "Vorname"],
    ["Elena", "Weiblicher Vorname"],
    ["Eli", "Geschlechtsneutraler Vorname"],
    ["Elia", "Vorname"],
    ["Eline", "Weiblicher Vorname"],
    ["Elis", "Geschlechtsneutraler Vorname"],
    ["Elisa", "Weiblicher Vorname"],
    ["Ellie", "Vorname"],
    ["Enid", "Weiblicher Vorname"],
    ["Erik", "Männlicher Vorname"],
    ["Erin", "Weiblicher Vorname"],
    ["Erni", "Vorname"],
    ["Ester", "Weiblicher Vorname"],
    ["Ethel", "Weiblicher Vorname"],
    ["Eva", "Weiblicher Vorname"],
    ["Faith", "Weiblicher Vorname"],
    ["Fanny", "Weiblicher Vorname"],
    ["Farah", "Vorname"],
    ["Fay", "Geschlechtsneutraler Vorname"],
    ["Femke", "Weiblicher Vorname"],
    ["Fran", "Weiblicher und männlicher Vorname"],
    ["Freya", "Weiblicher Vorname"],
    ["Gay", "Geschlechtsneutraler Vorname"],
    ["Geir", "Vorname"],
    ["Gerd", "Geschlechtsneutraler Vorname"],
    ["Gert", "Geschlechtsneutraler Vorname"],
    ["Gina", "Weiblicher Vorname"],
    ["Gro", "Weiblicher Vorname"],
    ["Halim", "Männlicher Vorname arabischer Herkunft"],
    ["Halla", "Vorname"],
    ["Hanne", "Weiblicher Vorname"],
    ["Heike", "Geschlechtsneutraler Vorname"],
    ["Helle", "Geschlechtsneutraler Vorname"],
    ["Helvi", "Vorname"],
    ["Henny", "Geschlechtsneutraler Vorname"],
    ["Hideo", "Männlicher Vorname (ひでお)"],
    ["Ihor", "Männlicher Vorname (Ігор)"],
    ["Iker", "Männlicher Vorname"],
    ["Ilana", "Weiblicher Vorname"],
    ["Ilja", "Männlicher oder weibliches Vorname"],
    ["Ilyas", "Männlicher Vorname (إلياس)"],
    ["Iman", "Vorname"],
    ["Inga", "Weiblicher Vorname"],
    ["Inge", "Geschlechtsneutraler Vorname"],
    ["Ira", "Geschlechtsneutraler Vorname"],
    ["Isa", "Geschlechtsneutraler Vorname"],
    ["Isao", "Männlicher Vorname"],
    ["Iva", "Geschlechtsneutraler Vorname"],
    ["Ivan", "Männlicher Vorname"],
    ["Ivar", "Männlicher Vorname"],
    ["Ivica", "Männlicher Vorname"],
    ["Ivo", "Männlicher Vorname"],
    ["Jaime", "Männlicher Vorname"],
    ["Jamie", "Geschlechtsneutraler Vorname"],
    ["Jane", "Geschlechtsneutraler Vorname"],
    ["Janis", "Vorname"],
    ["Janne", "Geschlechtsneutraler Vorname"],
    ["Jesse", "Männlicher Vorname"],
    ["Ji-min", "Geschlechtsneutraler Vorname (지민)"],
    ["Ji-u", "Geschlechtsneutraler Vorname (지우)"],
    ["Jill", "Weiblicher Vorname"],
    ["Joan", "Geschlechtsneutraler Vorname"],
    ["Joy", "Geschlechtsneutraler Vorname"],
    ["Joyce", "Geschlechtsneutraler Vorname"],
    ["June", "Geschlechtsneutraler Vorname"],
    ["Juri", "Männlicher Vorname (Юрий)"],
    ["Kaisa", "Vorname"],
    ["Kaori", "Weiblicher Vorname (かおり)"],
    ["Kaoru", "Vorname"],
    ["Kara", "Geschlechtsneutraler Vorname"],
    ["Karen", "Weiblicher Vorname"],
    ["Kari", "Geschlechtsneutraler Vorname"],
    ["Katia", "Weiblicher Vorname"],
    ["Kazuo", "Männlicher Vorname (かずお)"],
    ["Keiko", "Weiblicher Vorname (けいこ)"],
    ["Kelly", "Geschlechtsneutraler Vorname"],
    ["Kenji", "Männlicher Vorname (けんじ)"],
    ["Kenzo", "Männlicher Vorname"],
    ["Kim", "Geschlechtsneutraler Vorname"],
    ["Kumar", "Vorname"],
    ["Kusma", "Männlicher Vorname (Кузьма)"],
    ["Kyle", "Geschlechtsneutraler Vorname"],
    ["Leon", "Männlicher Vorname"],
    ["Lewis", "Männlicher Vorname"],
    ["Lila", "Weiblicher Vorname"],
    ["Line", "Weiblicher Vorname"],
    ["Linn", "Vorname"],
    ["Lou", "Geschlechtsneutraler Vorname"],
    ["Luca", "Geschlechtsneutraler Vorname"],
    ["Lukas", "Männlicher Vorname"],
    ["Madhu", "Geschlechtsneutraler Vorname"],
    ["Malak", "Vorname"],
    ["Malik", "Männlicher Vorname und Familienname"],
    ["Marie", "Geschlechtsneutraler Vorname"],
    ["Marin", "Geschlechtsneutraler Vorname"],
    ["Marjo", "Vorname"],
    ["Mary", "Weiblicher Vorname"],
    ["Masao", "Männlicher Vorname (まさお)"],
    ["Mateo", "Männlicher Vorname"],
    ["Max", "Männlicher Vorname"],
    ["Medea", "Weiblicher Vorname"],
    ["Meg", "Vorname"],
    ["Meng", "Chinesischer Nachname (孟)"],
    ["Miko", "Vorname"],
    ["Mila", "Geschlechtsneutraler Name"],
    ["Mio", "Vorname"],
    ["Miyu", "Japanischer weiblicher Vorname"],
    ["Mulay", "Vorname"],
    ["Nadir", "Männlicher Vorname"],
    ["Najma", "Weiblicher Vorname"],
    ["Nana", "Geschlechtsneutraler Vorname"],
    ["Naoki", "Männlicher Vorname (なおき)"],
    ["Naoto", "Männlicher Vorname"],
    ["Nico", "Männlicher Vorname"],
    ["Nigel", "Männlicher Vorname"],
    ["Nika", "Geschlechtsneutraler Vorname"],
    ["Nino", "Geschlechtsneutraler Vorname"],
    ["Noam", "Vorname"],
    ["Nobuo", "Männlicher Vorname (のぶお)"],
    ["Noemi", "Weiblicher Vorname"],
    ["Noor", "Vorname"],
    ["Nur", "Geschlechtsneutraler Vorname"],
    ["Ola", "Männlicher Vorname"],
    ["Pelin", "Männlicher Vorname"],
    ["Petra", "Weiblicher Vorname"],
    ["Pilar", "Weiblicher Vorname"],
    ["Priya", "Vorname"],
    ["Rajiv", "Männlicher Vorname"],
    ["Rana", "Vorname"],
    ["Randi", "Weiblicher Vorname"],
    ["Reza", "Vorname"],
    ["Rhys", "Geschlechtsneutraler Vorname"],
    ["Riku", "Vorname"],
    ["Riley", "Geschlechtsneutraler Vorname"],
    ["Robin", "Geschlechtsneutraler Vorname"],
    ["Romy", "Weiblicher Vorname"],
    ["Ronny", "Geschlechtsneutraler Vorname"],
    ["Ryan", "Geschlechtsneutraler Vorname"],
    ["Said", "Vorname"],
    ["Salih", "Männlicher Vorname (صالح)"],
    ["Sam", "Geschlechtsneutraler Vorname"],
    ["Sandy", "Geschlechtsneutraler Vorname"],
    ["Sanja", "Vorname"],
    ["Shi", "Familienname (史)"],
    ["Taavi", "Männlicher Vorname"],
    ["Taher", "Männlicher Vorname (طاهر)"],
    ["Talha", "Männlicher Vorname"],
    ["Taras", "Männlicher Vorname (Тарас)"],
    ["Tauno", "Männlicher Vorname"],
    ["Tea", "Vorname"],
    ["Telma", "Weiblicher Vorname"],
    ["Terje", "Männlicher Vorname"],
    ["Toini", "Vorname"],
    ["Toni", "Geschlechtsneutraler Vorname"],
    ["Tony", "Geschlechtsneutraler Vorname"],
    ["Tracy", "Vorname"],
    ["Ufuk", "Männlicher Vorname"],
    ["Ugo", "Männlicher Vorname"],
    ["Vanja", "Ein geschlechtsneutraler Vorname"],
    ["Vesa", "Vorname"],
    ["Vilja", "Weiblicher Vorname"],
    ["Vuk", "Männlicher Vorname"],
    ["Wadim", "Männlicher Vorname (Вадим)"],
    ["Wanda", "Weiblicher Vorname"],
    ["Yahya", "Vorname"],
    ["Yann", "Männlicher Vorname"],
    ["Yaqub", "Männlicher Vorname (يعقوب)"],
    ["Zina", "Weiblicher Vorname"],
    ["Zlata", "Weiblicher Vorname"],
    ["Zoe", "Weiblicher Vorname"]
  ]
}
