import type { Category } from './index'

// Automatisch erzeugt von scripts/harvest-wikidata.mjs.
// Quelle: Wikidata (Labels und Kurzbeschreibungen, CC0 — gemeinfrei).
// Nicht von Hand pflegen: der nächste Lauf überschreibt die Datei.
export const wdWerkzeug: Category = {
  id: "alltag",
  label: "Alltag & Essen",
  source: 'wikidata',
  entries: [
    ["Aalstecher", "Fischfangwerkzeug zum Aalfang"],
    ["Abbe-Prisma", "Spezielles Dispersionsprisma"],
    ["Aircrack", "Hackertool das auf WLANs abzielt"],
    ["Akkajaure", "Stausee in Schweden"],
    ["Aktivkohle", "Poröser, feinkörniger Kohlenstoff"],
    ["Alajuelasee", "Stausee in Panama"],
    ["Albignasee", "Stausee in Graubünden"],
    ["Aldusblatt", "Typografisches Zierornament (Fleuron)"],
    ["Altevatnet", "Stausee in Norwegen"],
    ["Altmühlsee", "Stausee in Bayern"],
    ["Arenal-See", "Stausee in Costa Rica"],
    ["Arnisee", "Ein Bergsee im Kanton Uri / Schweiz"],
    ["Asejire-Stausee", "See in Nigeria"],
    ["Astron", "Sowjetisches Weltraumteleskop"],
    ["Atomkriegsuhr", "Symbolische Uhr"],
    ["Außenspiegel", "Seitenspiegel an Autos"],
    ["Badovac-See", "Stausee im Kosovo"],
    ["Bain-Marie", "Küchengerät zum Warmhalten von Speisen"],
    ["Baldeneysee", "Stausee der Ruhr in Essen"],
    ["Bandscheibe", "Knorpelscheibe zwischen Wirbeln"],
    ["Batarang", "Fiktive Waffe des Superhelden Batman"],
    ["Berkemeyer", "Typusbezeichnung eines Trinkglasses"],
    ["Bethesda", "Zisterne in Jerusalem"],
    ["Blasenkammer", "Bauart für Teilchendetektoren"],
    ["Bleuel", "Schlagholz zum Wäschewaschen"],
    ["Briefumschlag", "Versandverpackung eines Briefes"],
    ["Bussole", "Kompass mit Peilvorrichtung"],
    ["Caliraya-See", "Stausee auf den Philippinen"],
    ["Carlsberg", "Dänischer Brauereikonzern"],
    ["Chorvoq", "Stausee des Chirchiq in Usbekistan"],
    ["Cinch", "Genormter Steckverbinder"],
    ["Debarsee", "Stausee in Nordmazedonien"],
    ["Derveni-Papyrus", "Griechisches Mauskript"],
    ["Destiny", "Modul der ISS"],
    ["Dnepr-Stausee", "Mündungsbereich des Flusses"],
    ["Dubrava-Stausee", "Stausee in Kroatien"],
    ["Earthship", "Gebäude in passiv-solarer Bauweise"],
    ["Edersee", "Talsperre in Nordhessen bei Waldeck"],
    ["Elektroskop", "Wissenschaftliches Gerät"],
    ["Engstlensee", "Natürlicher Stausee in der Schweiz"],
    ["Eudiometer", "Glasröhre zur Messung von Gasvolumina"],
    ["Euphratsee", "Stausee in Syrien"],
    ["Excalibur", "Mythisches Schwert in der Artussage"],
    ["Fahrradreifen", "Bauteil eines Fahrrads"],
    ["Fäustel", "Hammer mit meist quadratischen Bahnen"],
    ["Fedaiasee", "Stausee im Trentino, Italien"],
    ["Felge", "Teil des Rads, das den Reifen aufnimmt"],
    ["Feststellzange", "Einstellbarer arretierender Kniehebel"],
    ["Feuerstelle", "Offene Herdstelle"],
    ["Folienfilter", "Farbfilter in der Fotografie"],
    ["Forggensee", "Stausee in Bayern, Deutschland"],
    ["Gartenschlauch", "Schlauch zur Bewässerung des Gartens"],
    ["Gasthermometer", "Unterart eines Ausdehnungsthermometer"],
    ["Gaswagen", "Werkzeug"],
    ["Gelmersee", "Stausee in der Schweiz"],
    ["Glasflasche", "Flasche aus Glas"],
    ["Glasschneider", "Werkzeug zum Trennen von Glas"],
    ["Grasvatnet", "See in Norwegen und Schweden"],
    ["Gumbai", "Holzfächer beim Sumo"],
    ["Gungnir", "Name des Speeres von Odin"],
    ["Herschelkeil", "Werkzeug"],
    ["Hinode", "Japanischer Satellit"],
    ["Hinotori", "Japanischer Röntgensatellit"],
    ["Hisaki", "Japanischer Satellit"],
    ["Hitomi", "Japanischer Satellit"],
    ["Hosenrohr", "Rohre ineinander überführendes Bauteil"],
    ["Integral", "Gammastrahlen-Observatorium der ESA"],
    ["Intihuatana", "Archäologische Stätte in Peru"],
    ["Jerewan-See", "Stausee in Armenien"],
    ["Josua-Rolle", "Byzantinisches Manuskript"],
    ["Kamastausee", "Stausee in Russland"],
    ["Kankaria", "Ort und See in Ahmedabad, Indien"],
    ["Karajia", "Archäologische Stätte in Peru"],
    ["Kasan", "Großer Kochtopf aus Zentralasien"],
    ["Kenyir-See", "Stausee in Malaysia"],
    ["Kerkini-See", "Stausee in Griechenland"],
    ["Klapotetz", "Klapperndes Windrad"],
    ["Klöntalersee", "Stausee in der Schweiz"],
    ["Kockumskran", "Kran einer schwedischen Werft"],
    ["Koka-Stausee", "Stausee in Äthiopien"],
    ["Kolyma-Stausee", "Stausee in Russland"],
    ["Kopierstift", "Schreib- und Zeichengerät"],
    ["Koronas-Foton", "Russischer Sonnenforschungssatellit"],
    ["Kossoustausee", "Stausee in der Elfenbeinküste"],
    ["Kozjaksee", "See in Mazedonien"],
    ["Krantor", "Stadttor in Danzig"],
    ["Kurbelgehäuse", "Teil von Verbrennungsmotoren"],
    ["Kusanagi", "Legendäres japanisches Schwert"],
    ["Lachisch-Briefe", "21 beschriebene Tonscherben"],
    ["Langhantel", "Trainingsgerät für Krafttraining"],
    ["Langvatnet", "See in Norwegen, Fauske"],
    ["Lauwersmeer", "See in den Niederlanden"],
    ["Leslie-Würfel", "Werkzeug"],
    ["Lichtmaschine", "Elektrischer Generator"],
    ["Lightning", "Proprietäre Schnittstelle von Apple"],
    ["Luftschraube", "Werkzeug"],
    ["Lykurgos-Becher", "Spätantiker römischer Glasbecher"],
    ["Magellan", "Zwei optische Teleskope in Chile"],
    ["Mandau", "Schwert der Dayak aus Malaysia"],
    ["Mandra-See", "Stausee in Bulgarien"],
    ["Maota-See", "See im indischen Bundesstaat Rajasthan"],
    ["Marathon-See", "Stausee in Griechenland"],
    ["Marion-See", "Stausee in den Vereinigten Staaten"],
    ["Matkasee", "Stausee in Mazedonien"],
    ["Mavrovosee", "Stausee in Mazedonien"],
    ["Metalldetektor", "Gerät zur Lokalisierung von Metall"],
    ["Michel-Katalog", "Briefmarkenkatalog der Philatelisten"],
    ["Mini-VGA", "Elektrischer Steckertyp"],
    ["Motorblock", "Teil eines Verbrennungsmotors"],
    ["Muffe", "Verbindungselement für Rohre und Kabel"],
    ["Muhazi-See", "See in Ruanda"],
    ["Mülleimer", "Behälter, der Müll aufbewahrt"],
    ["Narva-Stausee", "Stausee zwischen Russland und Estland"],
    ["Nassersee", "Stausee in Ägypten und Sudan"],
    ["Nauka", "Modul der ISS"],
    ["Ninnion-Pinax", "Antike Tontafel"],
    ["Nonius", "Verkürzte Ableseskala"],
    ["Oberaarsee", "Stausee in der Schweiz"],
    ["Oborona", "Sowjetischen Radargerät"],
    ["Okutama-See", "Stausee in Japan"],
    ["Orava-Stausee", "Stausee in der Slowakei"],
    ["Osirak", "Irakische Atomreaktoren"],
    ["Överuman", "Stausee in Schweden und Norwegen"],
    ["Panharmonikon", "Historischer mechanischer Musikautomat"],
    ["Pascaline", "Mechanische Rechenmaschine"],
    ["Perservase", "Antiker apulischer Volutenkrater"],
    ["Perutscha-See", "Stausee in Kroatien"],
    ["Pfefferspray", "Werkzeug"],
    ["Pflugschar", "Schneide eines Pfuges"],
    ["Pirs", "Modul der ISS"],
    ["Piva-See", "Stausee in Montenegro"],
    ["Poisk", "Modul der ISS"],
    ["Portlandvase", "Römische Glas-Amphora"],
    ["Priroda", "Modul der Raumstation Mir"],
    ["Pritschal", "Modul der International Space Station"],
    ["Pulaski", "Zur Waldbrandbekämpfung"],
    ["Punktiergerät", "Messung in der Bildhauerei"],
    ["Puzhal-See", "Stausee in Indien"],
    ["Qaraoun-Stausee", "Stausee im Libanon"],
    ["Qiandao-See", "Stausee in China"],
    ["Qiru", "Historisches Trinkgefäß aus den Anden"],
    ["Radiosonde", "Meterologisches Messgerät"],
    ["Radkappe", "Abdeckung der Felge"],
    ["Rammsporn", "Werkzeug"],
    ["Rampenlicht", "Teil der Bühnenbeleuchtung"],
    ["Rasswet", "Modul der ISS"],
    ["Rechner", "Software von Apple"],
    ["Reichsschwert", "Bestandteil der Reichskleinodien"],
    ["Sagami-ko", "Stausee in Japan"],
    ["Sarja", "Modul der Internationalen Raumstation"],
    ["Sarsang-Stausee", "Stausee in Aserbaidschan"],
    ["Sassyk-See", "Stausee in der Ukraine"],
    ["Satpara-See", "Stausee in Pakistan"],
    ["Schabaka-Stein", "Altägyptische Stele"],
    ["Schiffenensee", "Stausee im Kanton Freiburg, Schweiz"],
    ["Schluchsee", "See in Deutschland"],
    ["Scott-Katalog", "US-amerikanischer Briefmarkenkatalog"],
    ["Sebilj", "Brunnen in Sarajevo"],
    ["Secchi-Scheibe", "Werkzeug"],
    ["Shamoji", "Japanisches Kochwerkzeug"],
    ["Skorradalsvatn", "See im Westen von Island"],
    ["Songavatn", "Stausee in Norwegen"],
    ["Sonnenkompass", "Tragbare Sonnenuhr"],
    ["Speibecken", "Wassergespülte Sanitäranlage"],
    ["Spektr", "Wissenschaftsmodul der Mir-Raumstation"],
    ["Spektr-UF", "Geplantes russisches Welraumteleskop"],
    ["Springform", "Backform mit Verschlussmechanismus"],
    ["Starina-Stausee", "Stausee in der Slowakei"],
    ["Storavan", "Stausee in Schweden"],
    ["Strandavatnet", "Stausee in Norwegen"],
    ["Stratos-Stausee", "Stausee in Griechenland"],
    ["Stratoscope", "Ballongetragenes Spiegelteleskop"],
    ["Stromwaage", "Werkzeug"],
    ["Swesda", "Wohn- und Navigationsmodul der ISS"],
    ["Szczerbiec", "Polnisches Krönungsschwert"],
    ["Tazza", "Flache, schüsselartige Trinkschale"],
    ["Tcpdump", "Freie Software"],
    ["Tenugui", "Japanisches Handtuch"],
    ["Theiß-See", "Stausee in Ungarn"],
    ["Thialf", "Halbtauchendes Kranschiff"],
    ["Tibi-Stausee", "Stausee in Spanien"],
    ["Tizona", "Schwert von El Cid Campeador"],
    ["Tranquility", "Modul der ISS"],
    ["Trappist", "Optisches Spiegelteleskop"],
    ["Tumbler", "Becherglas mit dickem Boden"],
    ["Turawa-Stausee", "Stausee in Polen"],
    ["Uhuru", "Weltraumteleskop für Röntgenstrahlung"],
    ["Unity", "Teil der ISS"],
    ["Vajra", "Buddhistisches Ritualobjekt"],
    ["Vel", "Göttlicher Speer der Hindumythologie"],
    ["Viliejskaje", "Stausee in Belarus"],
    ["Vlasinasee", "Stausee in Serbien"],
    ["Vyrnwy-Stausee", "Stausee im Vereinigten Königreich"],
    ["Wägitalersee", "Stausee in der Schweiz"],
    ["Wäschestärke", "Kleister, um Stoffe zu versteifen"],
    ["Wdzydze", "Stausee in Polen"],
    ["Weaver-Schiene", "Vorläufer der Picatinny-Schiene"],
    ["Wentian", "Modul der Chinesischen Raumstation"],
    ["Wesertalsperre", "Stausee in Belgien"],
    ["Wiljui-Stausee", "Stausee in Russland"],
    ["Windsack", "Meteorologisches Messgerät"],
    ["Wireshark", "Software zur Netzwerk-Analyse"],
    ["Wohlensee", "Stausee im Kanton Bern in der Schweiz"],
    ["Woronesch-Radar", "Russisches Frühwarnradarsystem"],
    ["Xinfeng-Stausee", "Stausee in China"],
    ["Zavoj-See", "Stausee in Serbien"],
    ["Zegrze-Stausee", "Stausee in Polen"],
    ["Zeitrad", "Sanduhr in Budapest, Ungarn"],
    ["Zervreilasee", "Stausee in der Schweiz"],
    ["Zlatarsee", "Stausee in Serbien"],
    ["Zwischenaufzug", "Energiespeicher mechanischer Uhren"]
  ]
}
